services:
  - type: web
    name: zerify-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=apps/backend/prisma/schema.prisma && npm run build --workspace=@zerify/backend
    startCommand: node apps/backend/dist/main.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: Zerify <notifications@zerify.in>
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        sync: false
