import { PrismaClient, UserRole, SocialPlatform, SocialAccountStatus, DemographicType, MediaType } from '@prisma/client';

const prisma = new PrismaClient();

export const FAKE_INFLUENCERS = [
  {
    email: 'marcus.tech@influencer.zerify.com',
    name: 'Marcus Vance',
    handle: '@marcustech',
    bio: 'Tech reviewer & AI engineer. Unboxing future gadgets, developer tools & AI apps. ⚡ 245K+ tech enthusiasts.',
    location: 'San Francisco, CA, United States',
    phoneCode: '+1',
    phoneNumber: '415-555-0192',
    dob: new Date('1995-06-14'),
    gender: 'Male',
    niches: ['Tech & Gadgets', 'Software & SaaS', 'AI & Machine Learning'],
    contentLanguages: ['English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['Dedicated Reel', 'YouTube Integration', 'Unboxing', 'Product Review'],
    minPricePerReel: 1200,
    currency: 'USD',
    responseTime: 'Within 6 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$1,200 – $3,500',
    paymentDetails: {
      bankName: 'JPMorgan Chase Bank',
      accountNumber: '****-****-4829',
      ifscCode: 'CHASUS33',
      paypalEmail: 'marcus.vance@paypal.me',
      panTaxId: 'US-TAX-8839201',
    },
    pastDeliverables: [
      {
        title: 'Aetheria AI Developer Suite In-Depth Workflow Demo',
        brandName: 'Aetheria Tech Labs',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C9182379',
        metrics: { views: 185000, likes: 14200, comments: 620, shares: 1940 },
      },
      {
        title: 'Top 5 AI Tools for Developers in 2026',
        brandName: 'CloudScale Analytics',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=tech_ai_top5',
        metrics: { views: 320000, likes: 28500, comments: 1420, shares: 3100 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_marcustech_101',
      username: 'marcustech',
      handle: '@marcustech',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
      followerCount: 245000,
      engagementRate: 4.2,
      profileUrl: 'https://instagram.com/marcustech',
      isVerified: true,
      accessToken: 'mock_token_marcustech',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'marcustech',
        displayName: 'Marcus Vance | Tech & AI',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
        bio: 'Tech reviewer & AI engineer. Unboxing future gadgets.',
        website: 'https://marcustech.io',
        profileUrl: 'https://instagram.com/marcustech',
        isVerified: true,
        followerCount: 245000,
        followingCount: 840,
        mediaCount: 312,
        category: 'Tech & Science',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 45.2 },
        { type: DemographicType.AGE_GENDER, key: '18-24.M', label: 'Male 18-24', value: 28.5 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 52.0 },
        { type: DemographicType.COUNTRY, key: 'IN', label: 'India', value: 18.4 },
      ],
      performance: [
        { recordedAt: new Date('2026-07-01'), reach: 520000, impressions: 890000, profileViews: 34000, websiteClicks: 4200, accountsEngaged: 48000, totalInteractions: 92000, followerCount: 240000, engagementRate: 4.1 },
        { recordedAt: new Date('2026-08-01'), reach: 580000, impressions: 960000, profileViews: 39000, websiteClicks: 4900, accountsEngaged: 54000, totalInteractions: 104000, followerCount: 245000, engagementRate: 4.2 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_001',
          mediaType: MediaType.REEL,
          caption: 'Testing out the new Aetheria AI developer copilot! Mind blown 🤯 #tech #ai #programming',
          permalink: 'https://instagram.com/reel/C9182379',
          thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-20'),
          likeCount: 14200,
          commentCount: 620,
          shareCount: 1940,
          saveCount: 850,
          playCount: 185000,
          reach: 160000,
          impressions: 210000,
        },
      ],
    },
  },
  {
    email: 'sophia.glow@influencer.zerify.com',
    name: 'Sophia Chen',
    handle: '@sophiaglow',
    bio: 'Clean beauty, glass skin routine & aesthetic skincare UGC creator ✨ Dermatology enthusiast.',
    location: 'Los Angeles, CA, United States',
    phoneCode: '+1',
    phoneNumber: '310-555-0184',
    dob: new Date('1998-11-22'),
    gender: 'Female',
    niches: ['Beauty & Skincare', 'Clean Beauty', 'Lifestyle'],
    contentLanguages: ['English', 'Mandarin'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Sponsored Post', 'TikTok Video', 'UGC Content', 'Story Takeover'],
    minPricePerReel: 650,
    currency: 'USD',
    responseTime: 'Within 12 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$650 – $1,800',
    paymentDetails: {
      bankName: 'Wells Fargo',
      accountNumber: '****-****-9102',
      ifscCode: 'WFBIUS6S',
      paypalEmail: 'sophia.chen@beauty.com',
      panTaxId: 'US-TAX-3948201',
    },
    pastDeliverables: [
      {
        title: '7-Day Alpine Serum Transformation Routine',
        brandName: 'GlowBotanica Organics',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C8219412',
        metrics: { views: 95000, likes: 9800, comments: 410, shares: 1100 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.TIKTOK,
      platformUserId: 'tt_sophiaglow_102',
      username: 'sophiaglow',
      handle: '@sophiaglow',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=500&q=80',
      followerCount: 115000,
      engagementRate: 3.8,
      profileUrl: 'https://tiktok.com/@sophiaglow',
      isVerified: false,
      accessToken: 'mock_token_sophiaglow',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'sophiaglow',
        displayName: 'Sophia Chen | Skincare & Glow',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=500&q=80',
        bio: 'Clean beauty, glass skin routine & aesthetic skincare UGC creator ✨',
        website: 'https://sophiaglow.com',
        profileUrl: 'https://tiktok.com/@sophiaglow',
        isVerified: false,
        followerCount: 115000,
        followingCount: 420,
        mediaCount: 185,
        category: 'Beauty, Cosmetics & Personal Care',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.F', label: 'Female 18-24', value: 58.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 31.2 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 65.0 },
        { type: DemographicType.COUNTRY, key: 'CA', label: 'Canada', value: 14.5 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 310000, impressions: 480000, profileViews: 18000, websiteClicks: 2100, accountsEngaged: 28000, totalInteractions: 44000, followerCount: 115000, engagementRate: 3.8 },
      ],
      contents: [
        {
          platformMediaId: 'media_tt_001',
          mediaType: MediaType.VIDEO,
          caption: 'Morning glass skin routine with organic botanical serum 🧴✨ #skincare #glassskin #glow',
          permalink: 'https://tiktok.com/@sophiaglow/video/739182391',
          thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-25'),
          likeCount: 9800,
          commentCount: 410,
          shareCount: 1100,
          saveCount: 2300,
          playCount: 95000,
          reach: 82000,
          impressions: 110000,
        },
      ],
    },
  },
  {
    email: 'david.miller@influencer.zerify.com',
    name: 'David Miller',
    handle: '@davidfit',
    bio: 'Pro Natural Bodybuilder & Athletic Performance Coach. Training routines, high-protein recipes & gear reviews 💪',
    location: 'Miami, FL, United States',
    phoneCode: '+1',
    phoneNumber: '305-555-0921',
    dob: new Date('1992-03-18'),
    gender: 'Male',
    niches: ['Fitness & Health', 'Gym Wear', 'Calisthenics & Nutrition'],
    contentLanguages: ['English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['Dedicated Reel', 'Brand Ambassador', 'Workout Video', 'Product Review'],
    minPricePerReel: 2000,
    currency: 'USD',
    responseTime: 'Within 2 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$2,000 – $4,500',
    paymentDetails: {
      bankName: 'Bank of America',
      accountNumber: '****-****-1192',
      ifscCode: 'BOFAUS3N',
      paypalEmail: 'david.miller@fitpro.com',
      panTaxId: 'US-TAX-5829104',
    },
    pastDeliverables: [
      {
        title: 'Full Body High-Intensity Cable Workout Showcase',
        brandName: 'ApexFit Performance Systems',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C7192834',
        metrics: { views: 410000, likes: 35000, comments: 1200, shares: 4800 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_davidfit_103',
      username: 'davidfit',
      handle: '@davidfit',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
      followerCount: 380000,
      engagementRate: 5.1,
      profileUrl: 'https://instagram.com/davidfit',
      isVerified: true,
      accessToken: 'mock_token_davidfit',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'davidfit',
        displayName: 'David Miller | Fitness Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
        bio: 'Pro Natural Bodybuilder & Athletic Performance Coach 💪',
        website: 'https://davidmillerfit.com',
        profileUrl: 'https://instagram.com/davidfit',
        isVerified: true,
        followerCount: 380000,
        followingCount: 510,
        mediaCount: 640,
        category: 'Fitness & Health',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 52.0 },
        { type: DemographicType.AGE_GENDER, key: '18-24.M', label: 'Male 18-24', value: 30.1 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 68.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 890000, impressions: 1450000, profileViews: 65000, websiteClicks: 8400, accountsEngaged: 98000, totalInteractions: 195000, followerCount: 380000, engagementRate: 5.1 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_003',
          mediaType: MediaType.REEL,
          caption: 'Back day routine with digital adaptive resistance cables 🔥 Save for later! #fitness #workout',
          permalink: 'https://instagram.com/reel/C7192834',
          thumbnailUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-15'),
          likeCount: 35000,
          commentCount: 1200,
          shareCount: 4800,
          saveCount: 8900,
          playCount: 410000,
          reach: 340000,
          impressions: 480000,
        },
      ],
    },
  },
  {
    email: 'emma.watson@influencer.zerify.com',
    name: 'Emma Watson-Smith',
    handle: '@emmathrifts',
    bio: 'Sustainable fashion stylist & vintage curator. Zero-waste wardrobe tips, OOTD & eco brand reviews 🌿',
    location: 'London, United Kingdom',
    phoneCode: '+44',
    phoneNumber: '20-7946-0192',
    dob: new Date('1997-04-10'),
    gender: 'Female',
    niches: ['Sustainable Fashion', 'Vintage & Thrifting', 'Eco-Living'],
    contentLanguages: ['English'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Styling Lookbook', 'IG Reel', 'TikTok Carousel', 'Unboxing'],
    minPricePerReel: 350,
    currency: 'USD',
    responseTime: 'Within 24 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$350 – $900',
    paymentDetails: {
      bankName: 'Barclays UK',
      accountNumber: '****-****-6721',
      ifscCode: 'BARCGB22',
      paypalEmail: 'emma.watson.smith@gmail.com',
      panTaxId: 'GB-VAT-9018239',
    },
    pastDeliverables: [
      {
        title: '3 Ways to Style Eco-Activewear Leggings',
        brandName: 'Veloce Activewear',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C5123908',
        metrics: { views: 42000, likes: 4500, comments: 210, shares: 540 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_emmathrifts_104',
      username: 'emmathrifts',
      handle: '@emmathrifts',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80',
      followerCount: 48000,
      engagementRate: 6.4,
      profileUrl: 'https://instagram.com/emmathrifts',
      isVerified: false,
      accessToken: 'mock_token_emmathrifts',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'emmathrifts',
        displayName: 'Emma Watson-Smith | Eco Style',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80',
        bio: 'Sustainable fashion stylist & vintage curator 🌿',
        website: 'https://emmathrifts.co.uk',
        profileUrl: 'https://instagram.com/emmathrifts',
        isVerified: false,
        followerCount: 48000,
        followingCount: 310,
        mediaCount: 420,
        category: 'Fashion & Apparel',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.F', label: 'Female 18-24', value: 48.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 42.0 },
        { type: DemographicType.COUNTRY, key: 'GB', label: 'United Kingdom', value: 72.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 110000, impressions: 180000, profileViews: 9500, websiteClicks: 1400, accountsEngaged: 14000, totalInteractions: 31000, followerCount: 48000, engagementRate: 6.4 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_004',
          mediaType: MediaType.CAROUSEL,
          caption: 'Thrift flip lookbook for autumn! Sustainable fashion can be chic 🍂 #sustainablefashion #thrift',
          permalink: 'https://instagram.com/p/C5123908',
          thumbnailUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-05-12'),
          likeCount: 4500,
          commentCount: 210,
          shareCount: 540,
          saveCount: 1200,
          playCount: 0,
          reach: 38000,
          impressions: 52000,
        },
      ],
    },
  },
  {
    email: 'chef.mateo@influencer.zerify.com',
    name: 'Mateo Rossi',
    handle: '@chefrrossi',
    bio: 'Italian Executive Chef & Culinary Creator in Milan 🍝 Quick gourmet recipes, handmade pasta & kitchen gadget tests.',
    location: 'Milan, Italy',
    phoneCode: '+39',
    phoneNumber: '02-555-9012',
    dob: new Date('1989-08-30'),
    gender: 'Male',
    niches: ['Food & Culinary Arts', 'Gourmet Recipes', 'Kitchenware'],
    contentLanguages: ['Italian', 'English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['Recipe Development', 'Instagram Reel', 'YouTube Cooking Video', 'Brand Sponsorship'],
    minPricePerReel: 900,
    currency: 'USD',
    responseTime: 'Within 12 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$900 – $2,200',
    paymentDetails: {
      bankName: 'Intesa Sanpaolo',
      accountNumber: '****-****-3312',
      ifscCode: 'BCITITMM',
      paypalEmail: 'mateo.rossi.chef@gmail.com',
      panTaxId: 'IT-VAT-3819204',
    },
    pastDeliverables: [
      {
        title: 'Single-Origin Ethiopian Espresso Tiramisu Recipe',
        brandName: 'Artisan Coffee Roastery',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C8192348',
        metrics: { views: 220000, likes: 21000, comments: 840, shares: 3200 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_chefrrossi_105',
      username: 'chefrrossi',
      handle: '@chefrrossi',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
      followerCount: 195000,
      engagementRate: 4.7,
      profileUrl: 'https://instagram.com/chefrrossi',
      isVerified: true,
      accessToken: 'mock_token_chefrrossi',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'chefrrossi',
        displayName: 'Chef Mateo Rossi',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
        bio: 'Italian Executive Chef & Culinary Creator in Milan 🍝',
        website: 'https://chefrrossi.it',
        profileUrl: 'https://instagram.com/chefrrossi',
        isVerified: true,
        followerCount: 195000,
        followingCount: 380,
        mediaCount: 510,
        category: 'Food & Gourmet Dining',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 41.0 },
        { type: DemographicType.AGE_GENDER, key: '35-44.F', label: 'Female 35-44', value: 29.0 },
        { type: DemographicType.COUNTRY, key: 'IT', label: 'Italy', value: 35.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 30.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 450000, impressions: 780000, profileViews: 31000, websiteClicks: 3900, accountsEngaged: 42000, totalInteractions: 91000, followerCount: 195000, engagementRate: 4.7 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_005',
          mediaType: MediaType.REEL,
          caption: 'Authentic 10-minute Truffle Tagliatelle! 🇮🇹 Recipe below 👇 #italianfood #pasta #chef',
          permalink: 'https://instagram.com/reel/C8192348',
          thumbnailUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-10'),
          likeCount: 21000,
          commentCount: 840,
          shareCount: 3200,
          saveCount: 7400,
          playCount: 220000,
          reach: 180000,
          impressions: 250000,
        },
      ],
    },
  },
  {
    email: 'liam.oconnor@influencer.zerify.com',
    name: "Liam O'Connor",
    handle: '@liamwanders',
    bio: 'Outdoor landscape photographer & drone pilot ⛰️ Exploring remote wilderness, camera gear & travel stay reviews.',
    location: 'Vancouver, BC, Canada',
    phoneCode: '+1',
    phoneNumber: '604-555-3819',
    dob: new Date('1994-01-25'),
    gender: 'Male',
    niches: ['Travel & Outdoor Photography', 'Adventure', 'Drone Cinematography'],
    contentLanguages: ['English'],
    availableForBarter: true,
    availableForRelocation: true,
    collaborationTypes: ['Travel VLOG', 'Hotel/Stay Review', 'Gear Showcase', 'High-Res Photo Licensing'],
    minPricePerReel: 850,
    currency: 'USD',
    responseTime: 'Within 24 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$850 – $2,000',
    paymentDetails: {
      bankName: 'Royal Bank of Canada',
      accountNumber: '****-****-8812',
      ifscCode: 'ROYCCAT2',
      paypalEmail: 'liam.wanders@photos.ca',
      panTaxId: 'CA-SIN-8901234',
    },
    pastDeliverables: [
      {
        title: 'Wilderness Camping with Solar Charging Rig',
        brandName: 'Solaris Living',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=liam_wild_solar',
        metrics: { views: 140000, likes: 11200, comments: 390, shares: 980 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.YOUTUBE,
      platformUserId: 'yt_liamwanders_106',
      username: 'liamwanders',
      handle: '@liamwanders',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
      followerCount: 160000,
      engagementRate: 4.0,
      profileUrl: 'https://youtube.com/@liamwanders',
      isVerified: true,
      accessToken: 'mock_token_liamwanders',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'liamwanders',
        displayName: "Liam O'Connor | Adventure Photos",
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
        bio: 'Outdoor landscape photographer & drone pilot ⛰️',
        website: 'https://liamwanders.com',
        profileUrl: 'https://youtube.com/@liamwanders',
        isVerified: true,
        followerCount: 160000,
        followingCount: 180,
        mediaCount: 190,
        category: 'Travel & Photography',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 49.0 },
        { type: DemographicType.COUNTRY, key: 'CA', label: 'Canada', value: 40.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 38.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 380000, impressions: 620000, profileViews: 22000, websiteClicks: 3100, accountsEngaged: 35000, totalInteractions: 64000, followerCount: 160000, engagementRate: 4.0 },
      ],
      contents: [
        {
          platformMediaId: 'media_yt_006',
          mediaType: MediaType.VIDEO,
          caption: '48 Hours Alone in Banff National Park (4K Cinematic Drone Vlog)',
          permalink: 'https://youtube.com/watch?v=liam_banff_4k',
          thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-28'),
          likeCount: 11200,
          commentCount: 390,
          shareCount: 980,
          saveCount: 1800,
          playCount: 140000,
          reach: 120000,
          impressions: 190000,
        },
      ],
    },
  },
  {
    email: 'alex.rivera@influencer.zerify.com',
    name: "Alex 'Vortex' Rivera",
    handle: '@vortexgame',
    bio: 'Twitch Partner & FPS Esports Streamer 🎮 Testing high refresh rate monitors, 8K mouse gear & custom magnetic keyboards.',
    location: 'Austin, TX, United States',
    phoneCode: '+1',
    phoneNumber: '512-555-0812',
    dob: new Date('2000-02-14'),
    gender: 'Male',
    niches: ['Gaming & Esports', 'PC Hardware', 'Streaming Setup'],
    contentLanguages: ['English', 'Spanish'],
    availableForBarter: false,
    availableForRelocation: false,
    collaborationTypes: ['Live Stream Sponsorship', 'Dedicated YouTube Video', 'Unboxing', 'Custom Overlay Banner'],
    minPricePerReel: 3500,
    currency: 'USD',
    responseTime: 'Within 4 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$3,500 – $8,000',
    paymentDetails: {
      bankName: 'Frost Bank Texas',
      accountNumber: '****-****-0019',
      ifscCode: 'FRSTUS44',
      paypalEmail: 'vortex.esports@gaming.com',
      panTaxId: 'US-TAX-1928374',
    },
    pastDeliverables: [
      {
        title: 'Testing Kroma 8KHz Mouse in Tournament Match',
        brandName: 'Kroma Gaming Gear',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=kroma_vortex_8k',
        metrics: { views: 580000, likes: 62000, comments: 2800, shares: 7400 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.YOUTUBE,
      platformUserId: 'yt_vortexgame_107',
      username: 'vortexgame',
      handle: '@vortexgame',
      avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=500&q=80',
      followerCount: 620000,
      engagementRate: 7.2,
      profileUrl: 'https://youtube.com/@vortexgame',
      isVerified: true,
      accessToken: 'mock_token_vortexgame',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'vortexgame',
        displayName: "Alex 'Vortex' Rivera | Gaming",
        avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=500&q=80',
        bio: 'Twitch Partner & FPS Esports Streamer 🎮',
        website: 'https://vortexesports.com',
        profileUrl: 'https://youtube.com/@vortexgame',
        isVerified: true,
        followerCount: 620000,
        followingCount: 210,
        mediaCount: 480,
        category: 'Gaming & Esports',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.M', label: 'Male 18-24', value: 65.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 25.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 60.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 1400000, impressions: 2800000, profileViews: 120000, websiteClicks: 18500, accountsEngaged: 210000, totalInteractions: 440000, followerCount: 620000, engagementRate: 7.2 },
      ],
      contents: [
        {
          platformMediaId: 'media_yt_007',
          mediaType: MediaType.VIDEO,
          caption: 'I tried an 8,000Hz polling rate gaming mouse... is it cheat code? 8K Hz test!',
          permalink: 'https://youtube.com/watch?v=kroma_vortex_8k',
          thumbnailUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-04'),
          likeCount: 62000,
          commentCount: 2800,
          shareCount: 7400,
          saveCount: 12000,
          playCount: 580000,
          reach: 490000,
          impressions: 720000,
        },
      ],
    },
  },
  {
    email: 'olivia.taylor@influencer.zerify.com',
    name: 'Olivia Taylor',
    handle: '@olivia_nest',
    bio: 'Nordic minimalist interior designer & home decor creator 🏡 Transforming small urban spaces with light & oak furniture.',
    location: 'Berlin, Germany',
    phoneCode: '+49',
    phoneNumber: '30-555-4819',
    dob: new Date('1996-09-05'),
    gender: 'Female',
    niches: ['Home & Interior Design', 'Minimalist Decor', 'DIY Home'],
    contentLanguages: ['German', 'English'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Room Makeover Reel', 'Pinterest Board Feature', 'Product Placement', 'UGC Video'],
    minPricePerReel: 400,
    currency: 'USD',
    responseTime: 'Within 12 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$400 – $1,000',
    paymentDetails: {
      bankName: 'N26 Bank Berlin',
      accountNumber: '****-****-7109',
      ifscCode: 'N26DEFF',
      paypalEmail: 'olivia.nest.design@gmail.com',
      panTaxId: 'DE-TAX-9821034',
    },
    pastDeliverables: [
      {
        title: 'Minimalist Apartment Living Room Makeover',
        brandName: 'Solaris Living',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C6190234',
        metrics: { views: 68000, likes: 6100, comments: 240, shares: 890 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_olivia_nest_108',
      username: 'olivia_nest',
      handle: '@olivia_nest',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=80',
      followerCount: 62000,
      engagementRate: 4.5,
      profileUrl: 'https://instagram.com/olivia_nest',
      isVerified: false,
      accessToken: 'mock_token_olivia_nest',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'olivia_nest',
        displayName: 'Olivia Taylor | Interior Styling',
        avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=80',
        bio: 'Nordic minimalist interior designer & home decor creator 🏡',
        website: 'https://olivianest.de',
        profileUrl: 'https://instagram.com/olivia_nest',
        isVerified: false,
        followerCount: 62000,
        followingCount: 390,
        mediaCount: 290,
        category: 'Home Decor & Interiors',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 54.0 },
        { type: DemographicType.COUNTRY, key: 'DE', label: 'Germany', value: 45.0 },
        { type: DemographicType.COUNTRY, key: 'FR', label: 'France', value: 20.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 140000, impressions: 220000, profileViews: 12000, websiteClicks: 1800, accountsEngaged: 16000, totalInteractions: 28000, followerCount: 62000, engagementRate: 4.5 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_008',
          mediaType: MediaType.REEL,
          caption: 'Transforming my living room nook with modular Scandinavian seating 🌿 #interiordesign #homedecor',
          permalink: 'https://instagram.com/reel/C6190234',
          thumbnailUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-01'),
          likeCount: 6100,
          commentCount: 240,
          shareCount: 890,
          saveCount: 1900,
          playCount: 68000,
          reach: 55000,
          impressions: 78000,
        },
      ],
    },
  },
  {
    email: 'satoshi.maya@influencer.zerify.com',
    name: 'Satoshi Maya',
    handle: '@crypto_maya',
    bio: 'Web3 researcher, DeFi yield strategist & Zero-Knowledge enthusiast 🌐 Educating 130K+ on smart contract protocols & crypto security.',
    location: 'Dubai, United Arab Emirates',
    phoneCode: '+971',
    phoneNumber: '50-555-8192',
    dob: new Date('1993-05-19'),
    gender: 'Male',
    niches: ['Web3 & Crypto', 'Blockchain', 'Financial Freedom'],
    contentLanguages: ['English', 'Arabic'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['Twitter Thread', 'YouTube Deep Dive', 'AMA Host', 'Keynote Presentation'],
    minPricePerReel: 1500,
    currency: 'USD',
    responseTime: 'Within 6 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$1,500 – $4,000',
    paymentDetails: {
      bankName: 'Emirates NBD',
      accountNumber: '****-****-4410',
      ifscCode: 'EBILAE2X',
      paypalEmail: 'maya.crypto@web3.io',
      panTaxId: 'AE-TAX-7719203',
    },
    pastDeliverables: [
      {
        title: 'Zero-Knowledge Rollup Cross-Chain Bridge Breakdown',
        brandName: 'ByteVerse Web3',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=zk_rollups_maya',
        metrics: { views: 92000, likes: 7400, comments: 510, shares: 1200 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.TWITTER,
      platformUserId: 'tw_crypto_maya_109',
      username: 'crypto_maya',
      handle: '@crypto_maya',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
      followerCount: 130000,
      engagementRate: 3.5,
      profileUrl: 'https://x.com/crypto_maya',
      isVerified: true,
      accessToken: 'mock_token_crypto_maya',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'crypto_maya',
        displayName: 'Satoshi Maya | Web3 Analyst',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
        bio: 'Web3 researcher, DeFi yield strategist & Zero-Knowledge enthusiast 🌐',
        website: 'https://cryptomaya.io',
        profileUrl: 'https://x.com/crypto_maya',
        isVerified: true,
        followerCount: 130000,
        followingCount: 520,
        mediaCount: 1420,
        category: 'Finance & Technology',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 68.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 35.0 },
        { type: DemographicType.COUNTRY, key: 'AE', label: 'UAE', value: 22.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 310000, impressions: 520000, profileViews: 19000, websiteClicks: 3400, accountsEngaged: 22000, totalInteractions: 45000, followerCount: 130000, engagementRate: 3.5 },
      ],
      contents: [
        {
          platformMediaId: 'media_tw_009',
          mediaType: MediaType.IMAGE,
          caption: 'Comprehensive thread on ZK-rollups security architecture 🧶🧵 (1/12)',
          permalink: 'https://x.com/crypto_maya/status/182930192',
          thumbnailUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-15'),
          likeCount: 7400,
          commentCount: 510,
          shareCount: 1200,
          saveCount: 3100,
          playCount: 0,
          reach: 85000,
          impressions: 140000,
        },
      ],
    },
  },
  {
    email: 'aarav.sharma@influencer.zerify.com',
    name: 'Aarav Sharma',
    handle: '@aarav_tech_in',
    bio: 'India’s leading smartphone & consumer tech reviewer 📱 Unboxing flagship phones, laptops & affordable gadgets in Hindi/English.',
    location: 'Bengaluru, Karnataka, India',
    phoneCode: '+91',
    phoneNumber: '98765-43210',
    dob: new Date('1996-12-01'),
    gender: 'Male',
    niches: ['Consumer Tech', 'Smartphones', 'EdTech & Gadgets'],
    contentLanguages: ['Hindi', 'English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['YouTube Unboxing', 'Instagram Reel', 'Brand Endorsement', 'Launch Event Host'],
    minPricePerReel: 600,
    currency: 'USD',
    responseTime: 'Within 4 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '₹45,000 – ₹1,20,000 ($600 – $1,500)',
    paymentDetails: {
      bankName: 'HDFC Bank Bengaluru',
      accountNumber: '****-****-9012',
      ifscCode: 'HDFC0001234',
      upiId: 'aarav.tech@hdfcbank',
      panTaxId: 'ABCPS9012K',
    },
    pastDeliverables: [
      {
        title: 'EduPulse STEM Robotics Kit Live Unboxing & Build',
        brandName: 'EduPulse Academy',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=aarav_edupulse_kit',
        metrics: { views: 380000, likes: 31000, comments: 1450, shares: 4200 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.YOUTUBE,
      platformUserId: 'yt_aarav_tech_110',
      username: 'aarav_tech_in',
      handle: '@aarav_tech_in',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
      followerCount: 420000,
      engagementRate: 5.8,
      profileUrl: 'https://youtube.com/@aarav_tech_in',
      isVerified: true,
      accessToken: 'mock_token_aarav_tech',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'aarav_tech_in',
        displayName: 'Aarav Sharma | Tech Reviews',
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
        bio: 'India’s leading smartphone & consumer tech reviewer 📱',
        website: 'https://aaravtech.in',
        profileUrl: 'https://youtube.com/@aarav_tech_in',
        isVerified: true,
        followerCount: 420000,
        followingCount: 290,
        mediaCount: 560,
        category: 'Science & Technology',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.M', label: 'Male 18-24', value: 55.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 35.0 },
        { type: DemographicType.COUNTRY, key: 'IN', label: 'India', value: 85.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 980000, impressions: 1800000, profileViews: 85000, websiteClicks: 12000, accountsEngaged: 110000, totalInteractions: 240000, followerCount: 420000, engagementRate: 5.8 },
      ],
      contents: [
        {
          platformMediaId: 'media_yt_010',
          mediaType: MediaType.VIDEO,
          caption: 'STEM Robotics & Coding Kit for Students! Honest Review & Assembly 🤖',
          permalink: 'https://youtube.com/watch?v=aarav_edupulse_kit',
          thumbnailUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-20'),
          likeCount: 31000,
          commentCount: 1450,
          shareCount: 4200,
          saveCount: 6800,
          playCount: 380000,
          reach: 310000,
          impressions: 450000,
        },
      ],
    },
  },
  {
    email: 'harper.family@influencer.zerify.com',
    name: 'Sarah & Jake Harper',
    handle: '@harperfamily',
    bio: 'Family of 4 sharing real parenting, eco-friendly kid products, home organization & weekend travel 👨‍👩‍👧‍👦',
    location: 'Toronto, ON, Canada',
    phoneCode: '+1',
    phoneNumber: '416-555-7190',
    dob: new Date('1991-07-12'),
    gender: 'Female',
    niches: ['Parenting & Family Lifestyle', 'Kidtech', 'Household Goods'],
    contentLanguages: ['English'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Family Lifestyle Vlog', 'Product Review Reel', 'TikTok Challenge', 'Blog Post'],
    minPricePerReel: 800,
    currency: 'USD',
    responseTime: 'Within 12 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$800 – $2,100',
    paymentDetails: {
      bankName: 'TD Canada Trust',
      accountNumber: '****-****-5521',
      ifscCode: 'TDOMCATTT',
      paypalEmail: 'harper.family@lifestyle.ca',
      panTaxId: 'CA-SIN-7718290',
    },
    pastDeliverables: [
      {
        title: 'Morning Routine with Organic Eco-Friendly Goods',
        brandName: 'EcoPack Solutions',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C7829103',
        metrics: { views: 110000, likes: 9400, comments: 380, shares: 1400 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_harperfamily_111',
      username: 'harperfamily',
      handle: '@harperfamily',
      avatar: 'https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&w=500&q=80',
      followerCount: 175000,
      engagementRate: 3.9,
      profileUrl: 'https://instagram.com/harperfamily',
      isVerified: true,
      accessToken: 'mock_token_harperfamily',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'harperfamily',
        displayName: 'The Harper Family | Life & Kids',
        avatarUrl: 'https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&w=500&q=80',
        bio: 'Family of 4 sharing real parenting & home organization 👨‍👩‍👧‍👦',
        website: 'https://harperfamilylife.com',
        profileUrl: 'https://instagram.com/harperfamily',
        isVerified: true,
        followerCount: 175000,
        followingCount: 610,
        mediaCount: 820,
        category: 'People & Parenting',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 58.0 },
        { type: DemographicType.AGE_GENDER, key: '35-44.F', label: 'Female 35-44', value: 32.0 },
        { type: DemographicType.COUNTRY, key: 'CA', label: 'Canada', value: 50.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 40.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 410000, impressions: 690000, profileViews: 28000, websiteClicks: 3200, accountsEngaged: 39000, totalInteractions: 68000, followerCount: 175000, engagementRate: 3.9 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_011',
          mediaType: MediaType.REEL,
          caption: 'Back to school organization hacks that saved our sanity! 🎒✏️ #parenting #familyhacks',
          permalink: 'https://instagram.com/reel/C7829103',
          thumbnailUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-02'),
          likeCount: 9400,
          commentCount: 380,
          shareCount: 1400,
          saveCount: 3100,
          playCount: 110000,
          reach: 92000,
          impressions: 130000,
        },
      ],
    },
  },
  {
    email: 'carlos.ruiz@influencer.zerify.com',
    name: 'Carlos Ruiz',
    handle: '@carlosdrives',
    bio: 'Automotive Journalist & EV Enthusiast in Madrid 🏎️ Test driving electric vehicles, hypercars & long-distance road trip range tests.',
    location: 'Madrid, Spain',
    phoneCode: '+34',
    phoneNumber: '91-555-0193',
    dob: new Date('1990-10-15'),
    gender: 'Male',
    niches: ['Automotive & EV', 'Supercars', 'Car Detailing'],
    contentLanguages: ['Spanish', 'English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['EV Range Test Video', 'Track Day Vlog', 'Instagram Reel', 'Car Launch Event'],
    minPricePerReel: 950,
    currency: 'USD',
    responseTime: 'Within 12 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$950 – $2,300',
    paymentDetails: {
      bankName: 'Banco Santander',
      accountNumber: '****-****-3391',
      ifscCode: 'BSCHESMM',
      paypalEmail: 'carlos.ruiz.drives@gmail.com',
      panTaxId: 'ES-VAT-0918234',
    },
    pastDeliverables: [
      {
        title: '500km European Highway Range Test with VoltDrive Moped & EV',
        brandName: 'VoltDrive Mobility',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=carlos_voltdrive_test',
        metrics: { views: 165000, likes: 13800, comments: 720, shares: 1800 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.YOUTUBE,
      platformUserId: 'yt_carlosdrives_112',
      username: 'carlosdrives',
      handle: '@carlosdrives',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
      followerCount: 140000,
      engagementRate: 4.8,
      profileUrl: 'https://youtube.com/@carlosdrives',
      isVerified: true,
      accessToken: 'mock_token_carlosdrives',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'carlosdrives',
        displayName: 'Carlos Ruiz | EV & Supercars',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
        bio: 'Automotive Journalist & EV Enthusiast in Madrid 🏎️',
        website: 'https://carlosdrives.es',
        profileUrl: 'https://youtube.com/@carlosdrives',
        isVerified: true,
        followerCount: 140000,
        followingCount: 240,
        mediaCount: 310,
        category: 'Autos & Vehicles',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 62.0 },
        { type: DemographicType.COUNTRY, key: 'ES', label: 'Spain', value: 50.0 },
        { type: DemographicType.COUNTRY, key: 'DE', label: 'Germany', value: 22.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 350000, impressions: 580000, profileViews: 21000, websiteClicks: 2900, accountsEngaged: 31000, totalInteractions: 67000, followerCount: 140000, engagementRate: 4.8 },
      ],
      contents: [
        {
          platformMediaId: 'media_yt_012',
          mediaType: MediaType.VIDEO,
          caption: 'Is this urban electric moped faster than metro traffic? City commuter test!',
          permalink: 'https://youtube.com/watch?v=carlos_voltdrive_test',
          thumbnailUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-18'),
          likeCount: 13800,
          commentCount: 720,
          shareCount: 1800,
          saveCount: 2400,
          playCount: 165000,
          reach: 140000,
          impressions: 210000,
        },
      ],
    },
  },
  {
    email: 'priya.patel@influencer.zerify.com',
    name: 'Priya Patel',
    handle: '@priyanyoga',
    bio: 'Certified Hatha & Vinyasa Yoga Teacher 🧘‍♀️ Daily mindfulness routines, breathwork techniques & holistic wellness tips.',
    location: 'Mumbai, Maharashtra, India',
    phoneCode: '+91',
    phoneNumber: '98200-11223',
    dob: new Date('1995-03-29'),
    gender: 'Female',
    niches: ['Wellness & Yoga', 'Mindfulness', 'Holistic Health'],
    contentLanguages: ['English', 'Hindi'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Guided Yoga Reel', 'Wellness Retreat Feature', 'Nutraceutical Review', 'Live Masterclass'],
    minPricePerReel: 350,
    currency: 'USD',
    responseTime: 'Within 6 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
    pricingRange: '₹25,000 – ₹60,000 ($350 – $800)',
    paymentDetails: {
      bankName: 'ICICI Bank Mumbai',
      accountNumber: '****-****-4490',
      ifscCode: 'ICIC0000982',
      upiId: 'priyapatel@icici',
      panTaxId: 'APZPP9812M',
    },
    pastDeliverables: [
      {
        title: 'Evening Stress-Relief Routine with KSM-66 Ashwagandha',
        brandName: 'NutraBio Wellness',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C8912301',
        metrics: { views: 88000, likes: 8100, comments: 340, shares: 1250 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_priyanyoga_113',
      username: 'priyanyoga',
      handle: '@priyanyoga',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
      followerCount: 85000,
      engagementRate: 5.2,
      profileUrl: 'https://instagram.com/priyanyoga',
      isVerified: false,
      accessToken: 'mock_token_priyanyoga',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'priyanyoga',
        displayName: 'Priya Patel | Yoga & Mindfulness',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
        bio: 'Certified Hatha & Vinyasa Yoga Teacher 🧘‍♀️',
        website: 'https://priyayoga.in',
        profileUrl: 'https://instagram.com/priyanyoga',
        isVerified: false,
        followerCount: 85000,
        followingCount: 420,
        mediaCount: 380,
        category: 'Health & Wellness',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 65.0 },
        { type: DemographicType.COUNTRY, key: 'IN', label: 'India', value: 78.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 190000, impressions: 320000, profileViews: 15000, websiteClicks: 2100, accountsEngaged: 24000, totalInteractions: 44000, followerCount: 85000, engagementRate: 5.2 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_013',
          mediaType: MediaType.REEL,
          caption: '15-minute bedtime yoga flow for deep sleep 🌙 Save for tonight! #yoga #wellness',
          permalink: 'https://instagram.com/reel/C8912301',
          thumbnailUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-12'),
          likeCount: 8100,
          commentCount: 340,
          shareCount: 1250,
          saveCount: 3900,
          playCount: 88000,
          reach: 72000,
          impressions: 105000,
        },
      ],
    },
  },
  {
    email: 'jordan.blake@influencer.zerify.com',
    name: 'Jordan Blake',
    handle: '@jordanbuilds',
    bio: 'B2B SaaS Founder & Tech Productivity Creator 🚀 Writing about startup growth, AI tools & developer workflows.',
    location: 'New York, NY, United States',
    phoneCode: '+1',
    phoneNumber: '212-555-9014',
    dob: new Date('1991-09-08'),
    gender: 'Male',
    niches: ['Business & Entrepreneurship', 'Productivity Apps', 'SaaS'],
    contentLanguages: ['English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['LinkedIn Newsletter Sponsorship', 'Twitter Thread', 'Podcast Guest', 'SaaS Case Study'],
    minPricePerReel: 500,
    currency: 'USD',
    responseTime: 'Within 6 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$500 – $1,400',
    paymentDetails: {
      bankName: 'Silicon Valley Bank (First Citizens)',
      accountNumber: '****-****-8819',
      ifscCode: 'SVBKUS6S',
      paypalEmail: 'jordan.blake@startups.com',
      panTaxId: 'US-TAX-4410923',
    },
    pastDeliverables: [
      {
        title: 'How FinOps Platforms Cut Cloud Infra Bills by 40%',
        brandName: 'CloudScale Analytics',
        contentType: 'Post',
        contentUrl: 'https://linkedin.com/posts/jordanbuilds_finops_cloud',
        metrics: { views: 54000, likes: 2900, comments: 180, shares: 410 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.LINKEDIN,
      platformUserId: 'li_jordanbuilds_114',
      username: 'jordanbuilds',
      handle: '@jordanbuilds',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
      followerCount: 55000,
      engagementRate: 4.1,
      profileUrl: 'https://linkedin.com/in/jordanbuilds',
      isVerified: true,
      accessToken: 'mock_token_jordanbuilds',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'jordanbuilds',
        displayName: 'Jordan Blake | SaaS & AI',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
        bio: 'B2B SaaS Founder & Tech Productivity Creator 🚀',
        website: 'https://jordanbuilds.com',
        profileUrl: 'https://linkedin.com/in/jordanbuilds',
        isVerified: true,
        followerCount: 55000,
        followingCount: 410,
        mediaCount: 220,
        category: 'Business & Entrepreneurship',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 45.0 },
        { type: DemographicType.AGE_GENDER, key: '35-44.M', label: 'Male 35-44', value: 38.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 65.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 120000, impressions: 210000, profileViews: 14000, websiteClicks: 2800, accountsEngaged: 15000, totalInteractions: 22000, followerCount: 55000, engagementRate: 4.1 },
      ],
      contents: [
        {
          platformMediaId: 'media_li_014',
          mediaType: MediaType.IMAGE,
          caption: '5 hard lessons I learned scaling our engineering team from 2 to 20. Thread below.',
          permalink: 'https://linkedin.com/posts/jordanbuilds_finops_cloud',
          thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-08'),
          likeCount: 2900,
          commentCount: 180,
          shareCount: 410,
          saveCount: 950,
          playCount: 0,
          reach: 48000,
          impressions: 72000,
        },
      ],
    },
  },
  {
    email: 'henri.montfort@influencer.zerify.com',
    name: 'Henri De Montfort',
    handle: '@henri_watches',
    bio: 'Swiss Horology Collector & High Watchmaking Critic ⌚ Reviewing independent watchmakers, tourbillons & vintage chronographs.',
    location: 'Geneva, Switzerland',
    phoneCode: '+41',
    phoneNumber: '22-555-1902',
    dob: new Date('1987-11-03'),
    gender: 'Male',
    niches: ['Luxury Goods', 'Swiss Horology', 'High Fashion'],
    contentLanguages: ['French', 'English'],
    availableForBarter: false,
    availableForRelocation: true,
    collaborationTypes: ['Macro Product Feature', 'Private Salon Host', 'Editorial Photo Shoot', 'Video Review'],
    minPricePerReel: 1200,
    currency: 'USD',
    responseTime: 'Within 24 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$1,200 – $3,000',
    paymentDetails: {
      bankName: 'UBS Geneva',
      accountNumber: '****-****-9921',
      ifscCode: 'UBSWCHZH',
      paypalEmail: 'henri.montfort@horology.ch',
      panTaxId: 'CH-CHE-9182301',
    },
    pastDeliverables: [
      {
        title: 'Hands-On Macro macro review of Titanium Tourbillon Caliber',
        brandName: 'Zenith Horology',
        contentType: 'Post',
        contentUrl: 'https://instagram.com/p/C9912093',
        metrics: { views: 32000, likes: 3800, comments: 190, shares: 410 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_henri_watches_115',
      username: 'henri_watches',
      handle: '@henri_watches',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
      followerCount: 39000,
      engagementRate: 3.1,
      profileUrl: 'https://instagram.com/henri_watches',
      isVerified: true,
      accessToken: 'mock_token_henri_watches',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'henri_watches',
        displayName: 'Henri De Montfort | Horology',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
        bio: 'Swiss Horology Collector & High Watchmaking Critic ⌚',
        website: 'https://henriwatches.ch',
        profileUrl: 'https://instagram.com/henri_watches',
        isVerified: true,
        followerCount: 39000,
        followingCount: 150,
        mediaCount: 310,
        category: 'Luxury Goods & Jewelry',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '35-44.M', label: 'Male 35-44', value: 52.0 },
        { type: DemographicType.AGE_GENDER, key: '45-54.M', label: 'Male 45-54', value: 30.0 },
        { type: DemographicType.COUNTRY, key: 'CH', label: 'Switzerland', value: 35.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 30.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 85000, impressions: 140000, profileViews: 7500, websiteClicks: 1200, accountsEngaged: 8900, totalInteractions: 1450, followerCount: 39000, engagementRate: 3.1 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_015',
          mediaType: MediaType.IMAGE,
          caption: 'Close-up inspect of the hand-carved sapphire crystal tourbillon cage 🔍 Titanium perfection.',
          permalink: 'https://instagram.com/p/C9912093',
          thumbnailUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-19'),
          likeCount: 3800,
          commentCount: 190,
          shareCount: 410,
          saveCount: 1100,
          playCount: 0,
          reach: 31000,
          impressions: 48000,
        },
      ],
    },
  },
  {
    email: 'jamal.brooks@influencer.zerify.com',
    name: 'Jamal Brooks',
    handle: '@kicksbybrooks',
    bio: 'Sneakerhead & Urban Streetwear Curator 👟 Unboxing limited drops, hypebeast fits & sneaker restoration tutorials.',
    location: 'Chicago, IL, United States',
    phoneCode: '+1',
    phoneNumber: '312-555-7781',
    dob: new Date('1999-01-17'),
    gender: 'Male',
    niches: ['Streetwear', 'Sneakerhead Culture', 'Hip-Hop Fashion'],
    contentLanguages: ['English'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Sneaker Unboxing Reel', 'OOTD TikTok', 'Event Appearance', 'Giveaway Campaign'],
    minPricePerReel: 1100,
    currency: 'USD',
    responseTime: 'Within 4 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$1,100 – $2,800',
    paymentDetails: {
      bankName: 'Chase Bank Chicago',
      accountNumber: '****-****-2201',
      ifscCode: 'CHASUS33',
      paypalEmail: 'jamal.brooks@kicks.com',
      panTaxId: 'US-TAX-9018239',
    },
    pastDeliverables: [
      {
        title: 'Top 5 Designer Eyewear Fits for Streetwear 2026',
        brandName: 'Starlight Eyewear',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C8901239',
        metrics: { views: 240000, likes: 22000, comments: 910, shares: 3800 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.TIKTOK,
      platformUserId: 'tt_kicksbybrooks_116',
      username: 'kicksbybrooks',
      handle: '@kicksbybrooks',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
      followerCount: 210000,
      engagementRate: 6.1,
      profileUrl: 'https://tiktok.com/@kicksbybrooks',
      isVerified: true,
      accessToken: 'mock_token_kicksbybrooks',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'kicksbybrooks',
        displayName: 'Jamal Brooks | Kicks & Fits',
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
        bio: 'Sneakerhead & Urban Streetwear Curator 👟',
        website: 'https://kicksbybrooks.com',
        profileUrl: 'https://tiktok.com/@kicksbybrooks',
        isVerified: true,
        followerCount: 210000,
        followingCount: 310,
        mediaCount: 390,
        category: 'Fashion & Footwear',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.M', label: 'Male 18-24', value: 62.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 28.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 75.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 590000, impressions: 980000, profileViews: 48000, websiteClicks: 6200, accountsEngaged: 65000, totalInteractions: 135000, followerCount: 210000, engagementRate: 6.1 },
      ],
      contents: [
        {
          platformMediaId: 'media_tt_016',
          mediaType: MediaType.VIDEO,
          caption: 'Rating the rarest 1-of-50 retro sneakers in my collection 🔥👟 #sneakers #streetwear',
          permalink: 'https://tiktok.com/@kicksbybrooks/video/891230192',
          thumbnailUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-01'),
          likeCount: 22000,
          commentCount: 910,
          shareCount: 3800,
          saveCount: 5400,
          playCount: 240000,
          reach: 195000,
          impressions: 280000,
        },
      ],
    },
  },
  {
    email: 'elena.rostova@influencer.zerify.com',
    name: 'Elena Rostova',
    handle: '@elena_codes',
    bio: 'Software Engineer & CS Educator 💻 Fullstack web dev tutorials, Rust code challenges & developer desk aesthetic setup.',
    location: 'Tallinn, Estonia',
    phoneCode: '+372',
    phoneNumber: '55-519-023',
    dob: new Date('1996-04-02'),
    gender: 'Female',
    niches: ['EdTech', 'Software Development', 'STEM Education'],
    contentLanguages: ['English', 'Estonian'],
    availableForBarter: true,
    availableForRelocation: true,
    collaborationTypes: ['Coding Bootcamp Sponsorship', 'YouTube Tutorial Integration', 'Tech Desk Setup Reel', 'Course Affiliate'],
    minPricePerReel: 450,
    currency: 'USD',
    responseTime: 'Within 6 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$450 – $1,200',
    paymentDetails: {
      bankName: 'Swedbank Estonia',
      accountNumber: '****-****-8812',
      ifscCode: 'HABAE22X',
      paypalEmail: 'elena.rostova@dev.io',
      panTaxId: 'EE-VAT-1092384',
    },
    pastDeliverables: [
      {
        title: 'Building a Fullstack Next.js App in 30 Minutes',
        brandName: 'EduPulse Academy',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=elena_nextjs_30m',
        metrics: { views: 125000, likes: 11400, comments: 620, shares: 1450 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.YOUTUBE,
      platformUserId: 'yt_elena_codes_117',
      username: 'elena_codes',
      handle: '@elena_codes',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
      followerCount: 72000,
      engagementRate: 5.5,
      profileUrl: 'https://youtube.com/@elena_codes',
      isVerified: false,
      accessToken: 'mock_token_elena_codes',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'elena_codes',
        displayName: 'Elena Rostova | Code & Tech',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
        bio: 'Software Engineer & CS Educator 💻',
        website: 'https://elenacodes.dev',
        profileUrl: 'https://youtube.com/@elena_codes',
        isVerified: false,
        followerCount: 72000,
        followingCount: 190,
        mediaCount: 140,
        category: 'Science & Education',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.F', label: 'Female 18-24', value: 38.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 42.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 35.0 },
        { type: DemographicType.COUNTRY, key: 'DE', label: 'Germany', value: 20.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 180000, impressions: 310000, profileViews: 14000, websiteClicks: 2400, accountsEngaged: 21000, totalInteractions: 39000, followerCount: 72000, engagementRate: 5.5 },
      ],
      contents: [
        {
          platformMediaId: 'media_yt_017',
          mediaType: MediaType.VIDEO,
          caption: 'Why I stopped using plain CSS for big Next.js projects 💡 Tailwind vs Vanilla CSS breakdown!',
          permalink: 'https://youtube.com/watch?v=elena_nextjs_30m',
          thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-25'),
          likeCount: 11400,
          commentCount: 620,
          shareCount: 1450,
          saveCount: 3100,
          playCount: 125000,
          reach: 105000,
          impressions: 160000,
        },
      ],
    },
  },
  {
    email: 'sam.bennett@influencer.zerify.com',
    name: 'Sam Bennett',
    handle: '@sambrews',
    bio: 'Specialty Coffee Barista & Espresso Nerd ☕ Dialing in single-origin beans, grinder testing & latte art technique in Melbourne.',
    location: 'Melbourne, VIC, Australia',
    phoneCode: '+61',
    phoneNumber: '3-9555-0192',
    dob: new Date('2001-08-11'),
    gender: 'Male',
    niches: ['Specialty Coffee', 'Espresso Gear', 'Cafe Reviews'],
    contentLanguages: ['English'],
    availableForBarter: true,
    availableForRelocation: false,
    collaborationTypes: ['Coffee Gear Review', 'Instagram Reel', 'TikTok Tasting', 'Bean Affiliate'],
    minPricePerReel: 200,
    currency: 'USD',
    responseTime: 'Within 2 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$200 – $500',
    paymentDetails: {
      bankName: 'Commonwealth Bank Australia',
      accountNumber: '****-****-3310',
      ifscCode: 'CTBAAU2S',
      paypalEmail: 'sam.brews.coffee@gmail.com',
      panTaxId: 'AU-ABN-88192039',
    },
    pastDeliverables: [
      {
        title: 'Testing Ethiopia Single-Origin Bean Extraction Profile',
        brandName: 'Artisan Coffee Roastery',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C7721092',
        metrics: { views: 28000, likes: 3200, comments: 140, shares: 420 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_sambrews_118',
      username: 'sambrews',
      handle: '@sambrews',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
      followerCount: 18000,
      engagementRate: 8.2,
      profileUrl: 'https://instagram.com/sambrews',
      isVerified: false,
      accessToken: 'mock_token_sambrews',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'sambrews',
        displayName: 'Sam Bennett | Specialty Coffee',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
        bio: 'Specialty Coffee Barista & Espresso Nerd ☕',
        website: 'https://sambrews.com.au',
        profileUrl: 'https://instagram.com/sambrews',
        isVerified: false,
        followerCount: 18000,
        followingCount: 220,
        mediaCount: 190,
        category: 'Food & Beverage',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 50.0 },
        { type: DemographicType.COUNTRY, key: 'AU', label: 'Australia', value: 65.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 45000, impressions: 72000, profileViews: 4100, websiteClicks: 650, accountsEngaged: 5800, totalInteractions: 14500, followerCount: 18000, engagementRate: 8.2 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_018',
          mediaType: MediaType.REEL,
          caption: 'How to dial in a light roast Ethiopian espresso shot like a champion barista ☕✨ #espresso #coffee',
          permalink: 'https://instagram.com/reel/C7721092',
          thumbnailUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-06-11'),
          likeCount: 3200,
          commentCount: 140,
          shareCount: 420,
          saveCount: 1100,
          playCount: 28000,
          reach: 22000,
          impressions: 34000,
        },
      ],
    },
  },
  {
    email: 'dr.zoe.martinez@influencer.zerify.com',
    name: 'Dr. Zoe Martinez',
    handle: '@drzoewellness',
    bio: 'Functional Medicine Physician & Longevity Researcher 🩺 Evidence-based wellness tips, gut microbiome health & supplement audits.',
    location: 'San Diego, CA, United States',
    phoneCode: '+1',
    phoneNumber: '619-555-8910',
    dob: new Date('1988-05-04'),
    gender: 'Female',
    niches: ['Healthcare & Nutrition', 'Functional Medicine', 'Supplements'],
    contentLanguages: ['English', 'Spanish'],
    availableForBarter: false,
    availableForRelocation: false,
    collaborationTypes: ['Medical Review Reel', 'Podcast Interview', 'Nutraceutical Endorsement', 'Keynote Speaker'],
    minPricePerReel: 1000,
    currency: 'USD',
    responseTime: 'Within 12 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$1,000 – $2,500',
    paymentDetails: {
      bankName: 'Bank of America San Diego',
      accountNumber: '****-****-9018',
      ifscCode: 'BOFAUS3N',
      paypalEmail: 'drzoe@functionalwellness.com',
      panTaxId: 'US-TAX-3829104',
    },
    pastDeliverables: [
      {
        title: 'Clinical Benefits of Clinical-Grade Nootropics for Focus',
        brandName: 'NeuroNourish Health',
        contentType: 'Reel',
        contentUrl: 'https://instagram.com/reel/C9019234',
        metrics: { views: 175000, likes: 14900, comments: 680, shares: 2400 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.INSTAGRAM,
      platformUserId: 'ig_drzoewellness_119',
      username: 'drzoewellness',
      handle: '@drzoewellness',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=500&q=80',
      followerCount: 150000,
      engagementRate: 4.6,
      profileUrl: 'https://instagram.com/drzoewellness',
      isVerified: true,
      accessToken: 'mock_token_drzoewellness',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'drzoewellness',
        displayName: 'Dr. Zoe Martinez | MD Wellness',
        avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=500&q=80',
        bio: 'Functional Medicine Physician & Longevity Researcher 🩺',
        website: 'https://drzoewellness.com',
        profileUrl: 'https://instagram.com/drzoewellness',
        isVerified: true,
        followerCount: 150000,
        followingCount: 310,
        mediaCount: 410,
        category: 'Health & Medical',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '25-34.F', label: 'Female 25-34', value: 48.0 },
        { type: DemographicType.AGE_GENDER, key: '35-44.F', label: 'Female 35-44', value: 35.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 70.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 390000, impressions: 680000, profileViews: 29000, websiteClicks: 3800, accountsEngaged: 36000, totalInteractions: 69000, followerCount: 150000, engagementRate: 4.6 },
      ],
      contents: [
        {
          platformMediaId: 'media_ig_019',
          mediaType: MediaType.REEL,
          caption: '3 science-backed ways to reduce cortisol naturally before 10 AM ☀️ #wellness #health #doctor',
          permalink: 'https://instagram.com/reel/C9019234',
          thumbnailUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-16'),
          likeCount: 14900,
          commentCount: 680,
          shareCount: 2400,
          saveCount: 5200,
          playCount: 175000,
          reach: 145000,
          impressions: 210000,
        },
      ],
    },
  },
  {
    email: 'leo.dupont@influencer.zerify.com',
    name: 'Leo Dupont',
    handle: '@leosoundlab',
    bio: 'Music Producer & Audio Gear Engineer in Paris 🎧 Testing studio planar headphones, analog synths & DAW plugins.',
    location: 'Paris, France',
    phoneCode: '+33',
    phoneNumber: '1-555-9018',
    dob: new Date('1994-07-21'),
    gender: 'Male',
    niches: ['Music Production', 'Audio Equipment', 'Synthesizers'],
    contentLanguages: ['French', 'English'],
    availableForBarter: true,
    availableForRelocation: true,
    collaborationTypes: ['Audio Gear Review Video', 'Instagram Reel sound demo', 'Sample Pack Release', 'Brand Sponsorship'],
    minPricePerReel: 500,
    currency: 'USD',
    responseTime: 'Within 6 hours',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    pricingRange: '$500 – $1,300',
    paymentDetails: {
      bankName: 'Société Générale Paris',
      accountNumber: '****-****-7712',
      ifscCode: 'SOGEFRPP',
      paypalEmail: 'leo.dupont.sound@gmail.com',
      panTaxId: 'FR-VAT-8819203',
    },
    pastDeliverables: [
      {
        title: 'Mixing Synthwave with Planar Magnetic Studio Headphones',
        brandName: 'VibeAudio Soundlabs',
        contentType: 'Video',
        contentUrl: 'https://youtube.com/watch?v=leo_vibeaudio_mix',
        metrics: { views: 84000, likes: 7900, comments: 310, shares: 920 },
      },
    ],
    socialAccount: {
      platform: SocialPlatform.YOUTUBE,
      platformUserId: 'yt_leosoundlab_120',
      username: 'leosoundlab',
      handle: '@leosoundlab',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
      followerCount: 92000,
      engagementRate: 4.9,
      profileUrl: 'https://youtube.com/@leosoundlab',
      isVerified: false,
      accessToken: 'mock_token_leosoundlab',
      status: SocialAccountStatus.CONNECTED,
      metadata: {
        username: 'leosoundlab',
        displayName: 'Leo Dupont | Sound Lab',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
        bio: 'Music Producer & Audio Gear Engineer in Paris 🎧',
        website: 'https://leosoundlab.fr',
        profileUrl: 'https://youtube.com/@leosoundlab',
        isVerified: false,
        followerCount: 92000,
        followingCount: 280,
        mediaCount: 160,
        category: 'Music & Audio',
      },
      demographics: [
        { type: DemographicType.AGE_GENDER, key: '18-24.M', label: 'Male 18-24', value: 45.0 },
        { type: DemographicType.AGE_GENDER, key: '25-34.M', label: 'Male 25-34', value: 40.0 },
        { type: DemographicType.COUNTRY, key: 'FR', label: 'France', value: 45.0 },
        { type: DemographicType.COUNTRY, key: 'US', label: 'United States', value: 25.0 },
      ],
      performance: [
        { recordedAt: new Date('2026-08-01'), reach: 210000, impressions: 380000, profileViews: 16000, websiteClicks: 2100, accountsEngaged: 23000, totalInteractions: 45000, followerCount: 92000, engagementRate: 4.9 },
      ],
      contents: [
        {
          platformMediaId: 'media_yt_020',
          mediaType: MediaType.VIDEO,
          caption: 'Are planar magnetic headphones worth $350 for music production? Sound test demo!',
          permalink: 'https://youtube.com/watch?v=leo_vibeaudio_mix',
          thumbnailUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=500&q=80',
          publishedAt: new Date('2026-07-08'),
          likeCount: 7900,
          commentCount: 310,
          shareCount: 920,
          saveCount: 1800,
          playCount: 84000,
          reach: 68000,
          impressions: 110000,
        },
      ],
    },
  },
];

async function main() {
  console.log('🌱 Seeding 20 Fake Influencer Profiles...');

  let count = 0;
  for (const item of FAKE_INFLUENCERS) {
    const user = await prisma.user.upsert({
      where: { email: item.email },
      update: {
        name: item.name,
        role: UserRole.INFLUENCER,
      },
      create: {
        email: item.email,
        name: item.name,
        role: UserRole.INFLUENCER,
      },
    });

    // Upsert Influencer Profile
    const influencerProfile = await prisma.influencerProfile.upsert({
      where: { userId: user.id },
      update: {
        handle: item.handle,
        bio: item.bio,
        location: item.location,
        phoneCode: item.phoneCode,
        phoneNumber: item.phoneNumber,
        dob: item.dob,
        gender: item.gender,
        niches: item.niches,
        contentLanguages: item.contentLanguages,
        availableForBarter: item.availableForBarter,
        availableForRelocation: item.availableForRelocation,
        collaborationTypes: item.collaborationTypes,
        minPricePerReel: item.minPricePerReel,
        currency: item.currency,
        responseTime: item.responseTime,
        avatarUrl: item.avatarUrl,
        pricingRange: item.pricingRange,
      },
      create: {
        userId: user.id,
        handle: item.handle,
        bio: item.bio,
        location: item.location,
        phoneCode: item.phoneCode,
        phoneNumber: item.phoneNumber,
        dob: item.dob,
        gender: item.gender,
        niches: item.niches,
        contentLanguages: item.contentLanguages,
        availableForBarter: item.availableForBarter,
        availableForRelocation: item.availableForRelocation,
        collaborationTypes: item.collaborationTypes,
        minPricePerReel: item.minPricePerReel,
        currency: item.currency,
        responseTime: item.responseTime,
        avatarUrl: item.avatarUrl,
        pricingRange: item.pricingRange,
      },
    });

    // Payment Details
    if (item.paymentDetails) {
      await prisma.influencerPaymentDetails.upsert({
        where: { influencerId: influencerProfile.id },
        update: {
          bankName: item.paymentDetails.bankName,
          accountNumber: item.paymentDetails.accountNumber,
          ifscCode: item.paymentDetails.ifscCode,
          paypalEmail: item.paymentDetails.paypalEmail,
          upiId: item.paymentDetails.upiId || null,
          panTaxId: item.paymentDetails.panTaxId,
        },
        create: {
          influencerId: influencerProfile.id,
          bankName: item.paymentDetails.bankName,
          accountNumber: item.paymentDetails.accountNumber,
          ifscCode: item.paymentDetails.ifscCode,
          paypalEmail: item.paymentDetails.paypalEmail,
          upiId: item.paymentDetails.upiId || null,
          panTaxId: item.paymentDetails.panTaxId,
        },
      });
    }

    // Past Deliverables
    if (item.pastDeliverables && item.pastDeliverables.length > 0) {
      await prisma.influencerPastDeliverable.deleteMany({ where: { influencerId: influencerProfile.id } });
      for (const del of item.pastDeliverables) {
        await prisma.influencerPastDeliverable.create({
          data: {
            influencerId: influencerProfile.id,
            title: del.title,
            brandName: del.brandName,
            contentType: del.contentType,
            contentUrl: del.contentUrl,
            metrics: del.metrics,
          },
        });
      }
    }

    // Social Account
    if (item.socialAccount) {
      const sa = item.socialAccount;
      
      // Delete existing social account for user & platform if exists
      const existingSa = await prisma.socialAccount.findFirst({
        where: { userId: user.id, platform: sa.platform },
      });

      if (existingSa) {
        await prisma.socialAccount.delete({ where: { id: existingSa.id } });
      }

      await prisma.socialAccount.create({
        data: {
          userId: user.id,
          platform: sa.platform,
          platformUserId: sa.platformUserId,
          username: sa.username,
          handle: sa.handle,
          avatar: sa.avatar,
          followerCount: sa.followerCount,
          engagementRate: sa.engagementRate,
          profileUrl: sa.profileUrl,
          isVerified: sa.isVerified,
          accessToken: sa.accessToken,
          status: sa.status,
          metadata: {
            create: sa.metadata,
          },
          demographics: {
            create: sa.demographics,
          },
          performance: {
            create: sa.performance,
          },
          contents: {
            create: sa.contents,
          },
        },
      });
    }

    count++;
    console.log(`  [${count}/20] Seeded Influencer: ${item.name} (${item.handle})`);
  }

  console.log(`\n🎉 Successfully seeded ${count} influencer profiles!`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding influencers:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
