import { PrismaClient, UserRole } from '@prisma/client';

const prisma = new PrismaClient();

function calculateCompletion(profileData: any, hasProducts: boolean): number {
  let percentage = 0;

  // 1. Company Info (20%)
  if (
    profileData.companyName &&
    profileData.website &&
    profileData.industry &&
    profileData.location &&
    profileData.description &&
    profileData.foundedYear
  ) {
    percentage += 20;
  } else if (profileData.companyName && profileData.industry) {
    percentage += 10;
  }

  // 2. Campaign Goals (20%)
  if (
    profileData.primaryGoals &&
    profileData.primaryGoals.length > 0 &&
    profileData.targetPlatforms &&
    profileData.targetPlatforms.length > 0 &&
    profileData.targetAudience
  ) {
    percentage += 20;
  } else if (profileData.primaryGoals && profileData.primaryGoals.length > 0) {
    percentage += 10;
  }

  // 3. Products/Services (20%)
  if (hasProducts) {
    percentage += 20;
  }

  // 4. Target Influencers (20%)
  if (
    profileData.creatorTiers &&
    profileData.creatorTiers.length > 0 &&
    profileData.creatorLocations &&
    profileData.creatorLocations.length > 0 &&
    profileData.campaignBudget &&
    profileData.campaignFrequency
  ) {
    percentage += 20;
  } else if (profileData.creatorTiers && profileData.creatorTiers.length > 0) {
    percentage += 10;
  }

  // 5. Escrow Setup (20%)
  if (
    profileData.escrowSetup &&
    profileData.escrowSetup.billingEmail &&
    profileData.escrowSetup.paymentMethod
  ) {
    percentage += 20;
  } else if (profileData.escrowSetup && profileData.escrowSetup.billingEmail) {
    percentage += 10;
  }

  return percentage;
}

const FAKE_COMPANIES = [
  // --- INITIAL 20 COMPANIES ---
  {
    email: 'aetheria@brand.zerify.com',
    companyName: 'Aetheria Tech Labs',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80',
    website: 'https://aetheria.io',
    industry: 'Software & SaaS',
    location: 'San Francisco, CA, United States',
    foundedYear: '2021',
    description: 'Next-generation AI workflow automation platform for high-velocity software developer teams.',
    socialLinks: {
      instagram: 'https://instagram.com/aetheriatech',
      linkedin: 'https://linkedin.com/company/aetheria',
      twitter: 'https://x.com/aetheria_ai',
      youtube: 'https://youtube.com/@aetheriatech',
    },
    brandValues: ['Innovation', 'Quality', 'Transparency'],
    primaryGoals: ['Lead Generation', 'User Acquisition', 'Brand Awareness'],
    targetPlatforms: ['LinkedIn', 'Twitter', 'YouTube'],
    targetAudience: {
      ageRanges: ['25-34', '35-44'],
      gender: 'All',
      locations: ['United States', 'United Kingdom', 'India'],
      interests: ['Artificial Intelligence & SaaS', 'Tech & Gadgets', 'Business & Entrepreneurship'],
    },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United States', 'United Kingdom'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.5,
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: {
      billingEmail: 'billing@aetheria.io',
      taxId: 'US-987654321',
      paymentMethod: 'Corporate Credit Card',
      escrowEnabled: true,
      autoDeposit: true,
      walletBalance: 25000,
    },
    products: [
      {
        name: 'Pro Developer AI Suite',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://aetheria.io/pro',
        category: 'Software & SaaS',
        price: '$199',
        description: 'Unlimited AI code generation, automated CI/CD pipeline auditing, and 24/7 dedicated developer support.',
      },
    ],
  },
  {
    email: 'glowbotanica@brand.zerify.com',
    companyName: 'GlowBotanica Organics',
    logoUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
    website: 'https://glowbotanica.com',
    industry: 'Beauty & Personal Care',
    location: 'Los Angeles, CA, United States',
    foundedYear: '2020',
    description: '100% organic, vegan & cruelty-free botanical skincare formulation infused with alpine flower extracts.',
    socialLinks: {
      instagram: 'https://instagram.com/glowbotanica',
      tiktok: 'https://tiktok.com/@glowbotanica',
      youtube: 'https://youtube.com/@glowbotanicabeauty',
    },
    brandValues: ['Sustainability', 'Quality', 'Inclusivity'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions', 'Content Creation'],
    targetPlatforms: ['Instagram', 'TikTok', 'YouTube'],
    targetAudience: {
      ageRanges: ['18-24', '25-34'],
      gender: 'Female',
      locations: ['United States', 'Canada', 'Australia'],
      interests: ['Beauty & Skincare', 'Wellness & Yoga', 'Fashion & Apparel'],
    },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States', 'Canada'],
    preferredCreatorGender: 'Female',
    verifiedOnly: false,
    minEngagementRate: 2.5,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: {
      billingEmail: 'finance@glowbotanica.com',
      paymentMethod: 'Bank Wire Transfer',
      escrowEnabled: true,
    },
    products: [
      {
        name: 'Hyaluronic Alpine Radiance Serum',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://glowbotanica.com/serum',
        category: 'Beauty, Cosmetics & Skincare',
        price: '$48',
        description: 'Deep hydration serum packed with triple molecular hyaluronic acid and rare alpine edelweiss extract.',
      },
    ],
  },
  {
    email: 'veloce@brand.zerify.com',
    companyName: 'Veloce Activewear',
    logoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=400&q=80',
    website: 'https://veloceapparel.it',
    industry: 'Fashion & Apparel',
    location: 'Milan, Italy',
    foundedYear: '2019',
    description: 'Italian engineered performance activewear designed for marathon runners and high-intensity urban athletes.',
    socialLinks: { instagram: 'https://instagram.com/veloce_official' },
    brandValues: ['Innovation', 'Quality'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: {
      ageRanges: ['18-24', '25-34', '35-44'],
      gender: 'All',
      locations: ['France', 'Germany', 'United Kingdom'],
      interests: ['Fitness & Health', 'Footwear & Sneakers', 'Sports & Athletics'],
    },
    creatorTiers: ['Micro', 'Mid', 'Macro'],
    creatorLocations: ['United Kingdom', 'Germany'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'accounts@veloceapparel.it', paymentMethod: 'Credit Card' },
    products: [
      {
        name: 'Veloce Ultra-Light Seamless Leggings',
        imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://veloceapparel.it/leggings',
        category: 'Footwear & Athleisure',
        price: '$85',
        description: 'Sweat-wicking 4-way stretch compressed seamless leggings with pocket storage.',
      },
    ],
  },
  {
    email: 'novapulse@brand.zerify.com',
    companyName: 'NovaPulse Energy',
    logoUrl: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=400&q=80',
    website: 'https://novapulseenergy.com',
    industry: 'Food & Beverage',
    location: 'Austin, TX, United States',
    foundedYear: '2022',
    description: 'Clean sparkling adaptogenic energy drinks with zero sugar, organic green tea caffeine, and lion mane mushrooms.',
    socialLinks: { instagram: 'https://instagram.com/novapulseenergy' },
    brandValues: ['Sustainability', 'Affordability'],
    primaryGoals: ['Product Launch', 'Brand Awareness'],
    targetPlatforms: ['Instagram', 'TikTok'],
    targetAudience: {
      ageRanges: ['18-24', '25-34'],
      gender: 'All',
      locations: ['United States'],
      interests: ['Food & Gourmet Dining', 'Gaming & Esports', 'Fitness & Health'],
    },
    creatorTiers: ['Nano', 'Micro'],
    creatorLocations: ['United States'],
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'pay@novapulseenergy.com', paymentMethod: 'ACH Transfer' },
    products: [
      {
        name: 'Wild Berry Adaptogen Energy (12 Pack)',
        imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://novapulseenergy.com/berry12',
        category: 'Beverages & Coffee',
        price: '$36',
        description: 'Refreshing sparkling water infused with 150mg organic caffeine, NALT, and cordyceps.',
      },
    ],
  },
  {
    email: 'apexfit@brand.zerify.com',
    companyName: 'ApexFit Performance Systems',
    logoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=400&q=80',
    website: 'https://apexfit.co.uk',
    industry: 'Fitness & Wellness',
    location: 'London, United Kingdom',
    foundedYear: '2018',
    description: 'AI-guided smart resistance workout equipment and biometric wearable trackers for elite home training.',
    brandValues: ['Innovation', 'Quality'],
    primaryGoals: ['Sales & Conversions', 'Lead Generation'],
    targetPlatforms: ['YouTube', 'Instagram'],
    targetAudience: {
      ageRanges: ['25-34', '35-44'],
      gender: 'All',
      locations: ['United Kingdom', 'United States'],
      interests: ['Fitness & Health', 'Supplements & Nutrition'],
    },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United Kingdom'],
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Ongoing Partnership',
    escrowSetup: { billingEmail: 'billing@apexfit.co.uk', paymentMethod: 'Stripe Escrow' },
    products: [
      {
        name: 'ApexFit Smart Cable Trainer Pro',
        imageUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://apexfit.co.uk/trainer',
        category: 'Fitness & Wellness',
        price: '$1,000+',
        description: 'Compact wall-mounted digital weight system generating up to 200lbs of smooth adaptive electronic resistance.',
      },
    ],
  },
  {
    email: 'kroma@brand.zerify.com',
    companyName: 'Kroma Gaming Gear',
    logoUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
    website: 'https://kromagaming.jp',
    industry: 'Consumer Electronics & Hardware',
    location: 'Tokyo, Japan',
    foundedYear: '2021',
    description: 'Ultra-lightweight 49g wireless optical gaming mice and custom magnetic hall-effect mechanical keyboards.',
    brandValues: ['Innovation', 'Quality'],
    primaryGoals: ['Product Launch', 'Community Building'],
    targetPlatforms: ['YouTube', 'TikTok', 'Twitter'],
    targetAudience: {
      ageRanges: ['18-24', '25-34'],
      gender: 'Male',
      locations: ['Japan', 'United States', 'Germany'],
      interests: ['Gaming & Esports', 'Tech & Gadgets'],
    },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States', 'Japan'],
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'One-time Campaign',
    escrowSetup: { billingEmail: 'accounts@kromagaming.jp', paymentMethod: 'Credit Card' },
    products: [
      {
        name: 'Kroma V2 Wireless 8KHz Gaming Mouse',
        imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://kromagaming.jp/v2mouse',
        category: 'Consumer Electronics & Hardware',
        price: '$129',
        description: 'Sub-0.1ms latency 8,000Hz polling rate sensor with optical switches and magnesium alloy chassis.',
      },
    ],
  },
  {
    email: 'solaris@brand.zerify.com',
    companyName: 'Solaris Living',
    logoUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=400&q=80',
    website: 'https://solarisliving.de',
    industry: 'Home & Interior Design',
    location: 'Berlin, Germany',
    foundedYear: '2020',
    description: 'Modular Scandinavian home furniture crafted from FSC-certified oak and recycled post-consumer ocean plastics.',
    brandValues: ['Sustainability', 'Quality'],
    primaryGoals: ['Brand Awareness', 'Content Creation'],
    targetPlatforms: ['Instagram', 'Pinterest'],
    targetAudience: {
      ageRanges: ['25-34', '35-44'],
      gender: 'All',
      locations: ['Germany', 'France'],
      interests: ['Home Decor & Interiors', 'Real Estate'],
    },
    creatorTiers: ['Micro'],
    creatorLocations: ['Germany'],
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'pay@solarisliving.de', paymentMethod: 'SEPA Transfer' },
    products: [
      {
        name: 'Solaris Modular Lounge Chair',
        imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://solarisliving.de/chair',
        category: 'Home Decor, Furniture & Interiors',
        price: '$349',
        description: 'Ergonomic lounge armchair upholstered in stain-resistant recycled wool fabric.',
      },
    ],
  },
  {
    email: 'nexa@brand.zerify.com',
    companyName: 'NEXA Digital Pay',
    logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=400&q=80',
    website: 'https://nexapay.sg',
    industry: 'Fintech & Digital Payments',
    location: 'Singapore, Singapore',
    foundedYear: '2022',
    description: 'Borderless multi-currency virtual credit card platform for digital nomads, freelancers, and remote startups.',
    brandValues: ['Transparency', 'Innovation'],
    primaryGoals: ['User Acquisition', 'Lead Generation'],
    targetPlatforms: ['LinkedIn', 'Twitter', 'YouTube'],
    targetAudience: {
      ageRanges: ['25-34', '35-44'],
      gender: 'All',
      locations: ['Singapore', 'India', 'Australia'],
      interests: ['Finance & Investing', 'Career & Productivity', 'Business & Entrepreneurship'],
    },
    creatorTiers: ['Mid'],
    creatorLocations: ['Singapore', 'India'],
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@nexapay.sg', paymentMethod: 'Wire Transfer' },
    products: [{ name: 'NEXA Nomad Corporate Card', category: 'Fintech & Digital Payments', price: 'Free' }],
  },
  {
    email: 'zenith@brand.zerify.com',
    companyName: 'Zenith Horology',
    logoUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
    website: 'https://zenithtimepieces.ch',
    industry: 'Luxury & Designer Goods',
    location: 'Geneva, Switzerland',
    foundedYear: '2015',
    description: 'Handcrafted Swiss automatic chronographs incorporating aerospace titanium and sapphire crystal backs.',
    brandValues: ['Quality'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'Male', locations: ['United States', 'Switzerland'], interests: ['Luxury & Designer Goods', 'Jewelry & Accessories'] },
    creatorTiers: ['Macro', 'Mega'],
    creatorLocations: ['United States', 'United Kingdom'],
    campaignBudget: '$50,000+',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'treasury@zenithtimepieces.ch', paymentMethod: 'Swiss Bank Wire' },
    products: [
      {
        name: 'Zenith Chrono-Tourbillon Titanium',
        imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=500&q=80',
        productUrl: 'https://zenithtimepieces.ch/tourbillon',
        category: 'Luxury Goods & Designer Fashion',
        price: '$1,000+',
        description: 'Caliber 400 self-winding movement with 72-hour power reserve housed in grade 5 titanium.',
      },
    ],
  },
  {
    email: 'nutrabio@brand.zerify.com',
    companyName: 'NutraBio Wellness',
    logoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80',
    website: 'https://nutrabiosciences.in',
    industry: 'Healthcare & Pharmaceuticals',
    location: 'Mumbai, Maharashtra, India',
    foundedYear: '2020',
    description: 'Ayurvedic nutraceutical supplements verified by clinical trials for digestive immunity and stress reduction.',
    brandValues: ['Quality', 'Community'],
    primaryGoals: ['Lead Generation', 'Sales & Conversions'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['India'], interests: ['Healthcare & Pharmaceuticals', 'Wellness & Yoga'] },
    creatorTiers: ['Micro'],
    creatorLocations: ['India'],
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'finance@nutrabio.in', paymentMethod: 'UPI Escrow' },
    products: [{ name: 'Ashwagandha KSM-66 Max Caps', category: 'Healthcare & Pharmaceuticals', price: '$24' }],
  },
  {
    email: 'byteverse@brand.zerify.com',
    companyName: 'ByteVerse Web3',
    logoUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=400&q=80',
    website: 'https://byteverse.io',
    industry: 'Web3, Crypto & Blockchain',
    location: 'Dubai, United Arab Emirates',
    foundedYear: '2022',
    description: 'Decentralized liquidity aggregator and cross-chain yield optimizer built on zero-knowledge rollups.',
    primaryGoals: ['User Acquisition', 'Community Building'],
    targetPlatforms: ['Twitter', 'Telegram', 'YouTube'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['United Arab Emirates', 'United States'], interests: ['Web3, Crypto & Blockchain'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['United States', 'United Arab Emirates'],
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@byteverse.io', paymentMethod: 'Crypto USDC Escrow' },
    products: [{ name: 'BytePass NFT Genesis VIP', category: 'Web3, Crypto & Blockchain', price: '$499' }],
  },
  {
    email: 'urbannest@brand.zerify.com',
    companyName: 'UrbanNest Realty',
    logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=400&q=80',
    website: 'https://urbannestproperties.ca',
    industry: 'Real Estate & Property Development',
    location: 'Toronto, Ontario, Canada',
    foundedYear: '2017',
    description: 'Boutique eco-friendly residential condo developments in prime metropolitan transit hubs.',
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['Instagram', 'Facebook', 'LinkedIn'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['Canada'], interests: ['Real Estate & Property'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['Canada'],
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'realestate@urbannest.ca', paymentMethod: 'Wire' },
    products: [{ name: 'Penthouse Condo VIP Priority Pass', category: 'Real Estate', price: '$1,000+' }],
  },
  {
    email: 'voltdrive@brand.zerify.com',
    companyName: 'VoltDrive Mobility',
    logoUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=400&q=80',
    website: 'https://voltdrive.se',
    industry: 'Automotive & EV',
    location: 'Stockholm, Sweden',
    foundedYear: '2021',
    description: 'Electric moped subscription service providing sustainable last-mile urban transport across Europe.',
    primaryGoals: ['Brand Awareness', 'User Acquisition'],
    targetPlatforms: ['Instagram', 'TikTok'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['Germany', 'Sweden'], interests: ['Automotive & EV'] },
    creatorTiers: ['Micro'],
    creatorLocations: ['Sweden', 'Germany'],
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'fleet@voltdrive.se', paymentMethod: 'Credit Card' },
    products: [{ name: 'Monthly VoltDrive Moped Pass', category: 'Automotive & EV', price: '$99' }],
  },
  {
    email: 'artisanroastery@brand.zerify.com',
    companyName: 'Artisan Coffee Roastery',
    logoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
    website: 'https://artisanroastery.com',
    industry: 'Beverages & Coffee',
    location: 'Seattle, WA, United States',
    foundedYear: '2016',
    description: 'Direct-trade single-origin specialty coffee beans micro-roasted daily in small 5kg copper drums.',
    primaryGoals: ['Sales & Conversions'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['United States'], interests: ['Beverages & Coffee'] },
    creatorTiers: ['Nano', 'Micro'],
    creatorLocations: ['United States'],
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'orders@artisanroastery.com', paymentMethod: 'Stripe' },
    products: [{ name: 'Ethiopia Yirgacheffe Whole Bean 1lb', category: 'Beverages & Coffee', price: '$22' }],
  },
  {
    email: 'edupulse@brand.zerify.com',
    companyName: 'EduPulse Academy',
    logoUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=400&q=80',
    website: 'https://edupulse.in',
    industry: 'EdTech & Education',
    location: 'Bengaluru, Karnataka, India',
    foundedYear: '2021',
    description: 'Interactive gamified STEM coding bootcamp for young innovators aged 8 to 16.',
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['YouTube', 'Facebook'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['India'], interests: ['EdTech & Education'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['India'],
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'admissions@edupulse.in', paymentMethod: 'Razorpay Escrow' },
    products: [{ name: 'Python & Robotics Masterclass 12-Wks', category: 'EdTech & Education', price: '$299' }],
  },
  {
    email: 'chronojewels@brand.zerify.com',
    companyName: 'ChronoJewels Atelier',
    logoUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=400&q=80',
    website: 'https://chronojewels.fr',
    industry: 'Jewelry & Accessories',
    location: 'Paris, France',
    foundedYear: '2019',
    description: 'Bespoke recycled 18k gold fine jewelry handcrafted in Parisian artisan workshops.',
    primaryGoals: ['Sales & Conversions'],
    targetPlatforms: ['Instagram', 'Pinterest'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'Female', locations: ['France', 'United Kingdom'], interests: ['Jewelry & Accessories'] },
    creatorTiers: ['Micro'],
    creatorLocations: ['France'],
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'finance@chronojewels.fr', paymentMethod: 'Credit Card' },
    products: [{ name: 'Solitaire Diamond 18k Gold Ring', category: 'Jewelry & Accessories', price: '$750' }],
  },
  {
    email: 'hyperstream@brand.zerify.com',
    companyName: 'HyperStream Esports',
    logoUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
    website: 'https://hyperstream.kr',
    industry: 'Esports & Gaming Organizations',
    location: 'Seoul, South Korea',
    foundedYear: '2023',
    description: 'Premier Asia-Pacific esports gaming organization hosting professional tournament leagues.',
    primaryGoals: ['Brand Awareness', 'Event Promotion'],
    targetPlatforms: ['YouTube', 'Twitch', 'Twitter'],
    targetAudience: { ageRanges: ['18-24'], gender: 'Male', locations: ['Japan', 'United States'], interests: ['Gaming & Esports'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United States', 'Japan'],
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'league@hyperstream.kr', paymentMethod: 'Bank Wire' },
    products: [{ name: 'HyperStream Official Team Jersey 2026', category: 'Gaming & Esports Enterprises', price: '$65' }],
  },
  {
    email: 'ecopack@brand.zerify.com',
    companyName: 'EcoPack Solutions',
    logoUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=400&q=80',
    website: 'https://ecopack.nl',
    industry: 'Non-Profit & Sustainability',
    location: 'Amsterdam, Netherlands',
    foundedYear: '2020',
    description: 'Biodegradable mushroom mycelium packaging solutions replacing Styrofoam for global shipping.',
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['LinkedIn'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['Germany', 'Netherlands'], interests: ['Non-Profit & Sustainability'] },
    creatorTiers: ['Micro'],
    creatorLocations: ['Germany'],
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'sustainability@ecopack.nl', paymentMethod: 'SEPA' },
    products: [{ name: 'Mushroom Packaging Starter Kit', category: 'Non-Profit & Sustainability', price: '$150' }],
  },
  {
    email: 'swiftcargo@brand.zerify.com',
    companyName: 'SwiftCargo Global',
    logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=400&q=80',
    website: 'https://swiftcargo.in',
    industry: 'Logistics & Supply Chain',
    location: 'Delhi, NCR, India',
    foundedYear: '2018',
    description: 'AI-driven cold-chain logistics network ensuring sub-24h fresh produce delivery across metropolitan hubs.',
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['LinkedIn'],
    targetAudience: { ageRanges: ['35-44'], gender: 'All', locations: ['India'], interests: ['Logistics & Supply Chain'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['India'],
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'ops@swiftcargo.in', paymentMethod: 'Bank Transfer' },
    products: [{ name: 'Cold-Chain Freight Express Booking', category: 'Logistics & Supply Chain', price: '$499' }],
  },
  {
    email: 'quantumdynamics@brand.zerify.com',
    companyName: 'Quantum Dynamics Inc.',
    logoUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=400&q=80',
    website: 'https://quantumdynamics.ai',
    industry: 'AI & Machine Learning',
    location: 'Boston, MA, United States',
    foundedYear: '2022',
    description: 'Quantum computing algorithm research lab developing fault-tolerant encryption algorithms for financial institutions.',
    primaryGoals: ['Brand Awareness'],
    targetPlatforms: ['Twitter', 'LinkedIn'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['United States'], interests: ['AI & Machine Learning'] },
    creatorTiers: ['Macro'],
    creatorLocations: ['United States'],
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'One-time Campaign',
    escrowSetup: { billingEmail: 'research@quantumdynamics.ai', paymentMethod: 'Wire' },
    products: [{ name: 'Quantum Key Distribution SDK', category: 'AI & Machine Learning', price: '$1,000+' }],
  },

  // --- 30 NEW 100% COMPLETED COMPANY PROFILES ---
  {
    email: 'starlight@brand.zerify.com',
    companyName: 'Starlight Eyewear',
    logoUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=400&q=80',
    website: 'https://starlighteyewear.com',
    industry: 'Fashion & Apparel',
    location: 'Los Angeles, CA, United States',
    foundedYear: '2021',
    description: 'Handcrafted acetate polarized sunglasses and blue-light blocking designer eyewear.',
    socialLinks: { instagram: 'https://instagram.com/starlighteyewear', tiktok: 'https://tiktok.com/@starlighteyewear' },
    brandValues: ['Innovation', 'Quality', 'Affordability'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions', 'Content Creation'],
    targetPlatforms: ['Instagram', 'TikTok', 'YouTube'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['United States', 'Canada'], interests: ['Fashion & Apparel', 'Luxury & Designer Goods'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States', 'Canada'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'pay@starlighteyewear.com', paymentMethod: 'Stripe Credit Card', escrowEnabled: true },
    products: [{ name: 'Starlight Polarized Aviator Sunglasses', imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=500&q=80', category: 'Jewelry & Accessories', price: '$110', description: 'Italian bio-acetate frame with Category 3 UV400 anti-glare polarized lenses.' }],
  },
  {
    email: 'kinetic@brand.zerify.com',
    companyName: 'Kinetic E-Bikes',
    logoUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=400&q=80',
    website: 'https://kineticbikes.com',
    industry: 'Automotive & EV',
    location: 'Portland, OR, United States',
    foundedYear: '2020',
    description: 'Lightweight urban commuter electric bikes featuring removable torque-sensing battery packs.',
    socialLinks: { instagram: 'https://instagram.com/kineticbikes', youtube: 'https://youtube.com/@kineticbikes' },
    brandValues: ['Sustainability', 'Innovation', 'Quality'],
    primaryGoals: ['Sales & Conversions', 'Brand Awareness'],
    targetPlatforms: ['YouTube', 'Instagram'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['United States', 'Germany'], interests: ['Automotive & EV', 'Outdoor & Camping'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 2.8,
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'finance@kineticbikes.com', paymentMethod: 'Corporate Wire', escrowEnabled: true },
    products: [{ name: 'Kinetic City Pro E-Bike 750W', imageUrl: 'https://images.unsplash.com/photo-1571068316344-75ad76973297?auto=format&fit=crop&w=500&q=80', category: 'Automotive & EV', price: '$1,000+', description: '70-mile range electric commuter bicycle with hydraulic disc brakes and integrated LED headlight.' }],
  },
  {
    email: 'pureoasis@brand.zerify.com',
    companyName: 'PureOasis Skincare',
    logoUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=400&q=80',
    website: 'https://pureoasisskincare.com',
    industry: 'Beauty & Personal Care',
    location: 'Miami, FL, United States',
    foundedYear: '2021',
    description: 'Dermatologist-tested coral-reef safe sunscreen and sun-care antioxidants.',
    socialLinks: { instagram: 'https://instagram.com/pureoasis' },
    brandValues: ['Sustainability', 'Quality'],
    primaryGoals: ['Brand Awareness', 'Content Creation'],
    targetPlatforms: ['Instagram', 'TikTok'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'Female', locations: ['United States', 'Australia'], interests: ['Beauty & Skincare', 'Wellness & Yoga'] },
    creatorTiers: ['Nano', 'Micro'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Female',
    verifiedOnly: false,
    minEngagementRate: 2.0,
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@pureoasisskincare.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'PureOasis Mineral Sunscreen SPF 50', category: 'Beauty, Cosmetics & Skincare', price: '$32', description: 'Non-nano zinc oxide lightweight facial sunblock with niacinamide.' }],
  },
  {
    email: 'vibeaudio@brand.zerify.com',
    companyName: 'VibeAudio Soundlabs',
    logoUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
    website: 'https://vibeaudiosound.com',
    industry: 'Consumer Electronics & Hardware',
    location: 'San Jose, CA, United States',
    foundedYear: '2019',
    description: 'Studio-grade planar magnetic wireless noise-canceling headphones for audiophiles and podcasters.',
    socialLinks: { instagram: 'https://instagram.com/vibeaudiosound', youtube: 'https://youtube.com/@vibeaudio' },
    brandValues: ['Quality', 'Innovation'],
    primaryGoals: ['Product Launch', 'Sales & Conversions'],
    targetPlatforms: ['YouTube', 'Twitter', 'Instagram'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['United States', 'United Kingdom', 'Germany'], interests: ['Consumer Electronics & Hardware', 'Music & Audio'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United States', 'United Kingdom'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.2,
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'accounts@vibeaudiosound.com', paymentMethod: 'Corporate ACH', escrowEnabled: true },
    products: [{ name: 'VibeStudio ANC Planar Headphones', category: 'Consumer Electronics & Hardware', price: '$349', description: 'High-res audio certified, 50mm planar magnetic drivers with active noise cancellation.' }],
  },
  {
    email: 'neuronourish@brand.zerify.com',
    companyName: 'NeuroNourish Health',
    logoUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=400&q=80',
    website: 'https://neuronourishhealth.com',
    industry: 'Fitness & Wellness',
    location: 'Boston, MA, United States',
    foundedYear: '2022',
    description: 'Nootropic brain performance capsules formulated by MIT neuroscientists for cognitive focus.',
    socialLinks: { instagram: 'https://instagram.com/neuronourish' },
    brandValues: ['Quality', 'Transparency'],
    primaryGoals: ['Lead Generation', 'Sales & Conversions'],
    targetPlatforms: ['YouTube', 'Instagram', 'LinkedIn'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['United States'], interests: ['Fitness & Health', 'Career & Productivity'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.5,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'pay@neuronourishhealth.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'NeuroNourish Focus Formula 60 Caps', category: 'Fitness & Wellness', price: '$59', description: 'Clinical dose Alpha-GPC, Bacopa Monnieri, and L-Theanine for sustained mental clarity.' }],
  },
  {
    email: 'cloudscale@brand.zerify.com',
    companyName: 'CloudScale Analytics',
    logoUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=400&q=80',
    website: 'https://cloudscale.io',
    industry: 'Software & SaaS',
    location: 'Seattle, WA, United States',
    foundedYear: '2019',
    description: 'Real-time multi-cloud infrastructure cost observability platform for Kubernetes clusters.',
    socialLinks: { linkedin: 'https://linkedin.com/company/cloudscale', twitter: 'https://x.com/cloudscale_io' },
    brandValues: ['Innovation', 'Transparency'],
    primaryGoals: ['Lead Generation', 'User Acquisition'],
    targetPlatforms: ['LinkedIn', 'Twitter'],
    targetAudience: { ageRanges: ['25-34', '35-44', '45-54'], gender: 'All', locations: ['United States', 'United Kingdom'], interests: ['Software & SaaS', 'Cybersecurity & IT'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$10,000 – $25,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@cloudscale.io', paymentMethod: 'Corporate Wire', escrowEnabled: true },
    products: [{ name: 'CloudScale K8s FinOps Suite', category: 'Software & SaaS', price: '$499', description: 'Automated idle node downsizing, spot instance orchestrator, and real-time slack cost alerts.' }],
  },
  {
    email: 'zenbite@brand.zerify.com',
    companyName: 'ZenBite Protein',
    logoUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
    website: 'https://zenbiteprotein.com',
    industry: 'Food & Beverage',
    location: 'Chicago, IL, United States',
    foundedYear: '2021',
    description: 'Organic non-GMO pea protein snacks and plant-based protein bars with zero artificial sweeteners.',
    socialLinks: { instagram: 'https://instagram.com/zenbiteprotein' },
    brandValues: ['Sustainability', 'Quality'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions'],
    targetPlatforms: ['Instagram', 'TikTok'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['United States'], interests: ['Food & Gourmet Dining', 'Fitness & Health'] },
    creatorTiers: ['Nano', 'Micro'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.0,
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'finance@zenbiteprotein.com', paymentMethod: 'Credit Card', escrowEnabled: true },
    products: [{ name: 'ZenBite Dark Chocolate Peanut Protein Bars (12 Pack)', category: 'Food & Gourmet Snacks', price: '$34', description: '15g plant protein, 2g sugar, organic cocoa and roasted peanuts.' }],
  },
  {
    email: 'velox@brand.zerify.com',
    companyName: 'Velox CyberSecurity',
    logoUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=400&q=80',
    website: 'https://veloxsecurity.com',
    industry: 'Cybersecurity & IT Infrastructure',
    location: 'New York, NY, United States',
    foundedYear: '2018',
    description: 'Automated endpoint security and identity threat detection platform for mid-market enterprises.',
    socialLinks: { linkedin: 'https://linkedin.com/company/veloxsecurity' },
    brandValues: ['Quality', 'Innovation'],
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['LinkedIn', 'Twitter'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['United States', 'United Kingdom'], interests: ['Cybersecurity & IT'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.5,
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'accounts@veloxsecurity.com', paymentMethod: 'ACH Wire', escrowEnabled: true },
    products: [{ name: 'Velox XDR Threat Intelligence Agent', category: 'Cybersecurity & IT Infrastructure', price: '$999', description: 'Zero-trust endpoint telemetry monitoring with real-time ransomware auto-isolation.' }],
  },
  {
    email: 'luminaoptics@brand.zerify.com',
    companyName: 'Lumina Mobile Apps',
    logoUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=400&q=80',
    website: 'https://luminaapps.kr',
    industry: 'Mobile Apps & Gaming',
    location: 'Seoul, South Korea',
    foundedYear: '2022',
    description: 'AI camera enhancement and creative video editing smartphone app with 50M+ downloads.',
    socialLinks: { instagram: 'https://instagram.com/luminaapp', tiktok: 'https://tiktok.com/@luminaapp' },
    brandValues: ['Innovation', 'Affordability'],
    primaryGoals: ['User Acquisition', 'App Downloads & Installs'],
    targetPlatforms: ['TikTok', 'Instagram'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['Japan', 'United States', 'South Korea'], interests: ['Mobile Apps & Gaming', 'Photography & Videography'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States', 'Japan'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.8,
    campaignBudget: '$10,000 – $25,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'dev@luminaapps.kr', paymentMethod: 'PayPal Corporate', escrowEnabled: true },
    products: [{ name: 'Lumina Pro Video Creator Pass (1 Year)', category: 'Mobile Apps & Mobile Gaming', price: '$49', description: 'Unlock 4K 120fps AI color grading filters, automatic captioning, and background removal.' }],
  },
  {
    email: 'auracraft@brand.zerify.com',
    companyName: 'AuraCraft Decor',
    logoUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=400&q=80',
    website: 'https://auracraft.dk',
    industry: 'Home & Interior Design',
    location: 'Copenhagen, Denmark',
    foundedYear: '2020',
    description: 'Handcrafted ceramic vase collections, dimmable ambient warm lighting fixtures, and linen textiles.',
    socialLinks: { instagram: 'https://instagram.com/auracraft_cph', pinterest: 'https://pinterest.com/auracraft' },
    brandValues: ['Quality', 'Sustainability'],
    primaryGoals: ['Brand Awareness', 'Content Creation'],
    targetPlatforms: ['Instagram', 'Pinterest'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'Female', locations: ['United Kingdom', 'Germany', 'Denmark'], interests: ['Home Decor, Furniture & Interiors'] },
    creatorTiers: ['Micro'],
    creatorLocations: ['United Kingdom', 'Germany'],
    preferredCreatorGender: 'Female',
    verifiedOnly: false,
    minEngagementRate: 2.2,
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'billing@auracraft.dk', paymentMethod: 'SEPA Transfer', escrowEnabled: true },
    products: [{ name: 'AuraCraft Nordic Ceramic Table Lamp', category: 'Home Decor, Furniture & Interiors', price: '$145', description: 'Hand-thrown stoneware lamp base with unbleached organic linen lampshade.' }],
  },

  // 11-20
  {
    email: 'terragreen@brand.zerify.com',
    companyName: 'TerraGreen CleanTech',
    logoUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=400&q=80',
    website: 'https://terragreentech.nl',
    industry: 'Non-Profit & Sustainability',
    location: 'Amsterdam, Netherlands',
    foundedYear: '2019',
    description: 'Residential micro solar panel systems and home battery energy storage solutions.',
    socialLinks: { linkedin: 'https://linkedin.com/company/terragreen' },
    brandValues: ['Sustainability', 'Innovation'],
    primaryGoals: ['Lead Generation', 'Brand Awareness'],
    targetPlatforms: ['LinkedIn', 'Facebook'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['Netherlands', 'Germany'], interests: ['Clean Energy & Sustainability'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['Netherlands', 'Germany'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 2.5,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'finance@terragreentech.nl', paymentMethod: 'SEPA', escrowEnabled: true },
    products: [{ name: 'TerraHome 5kWh Battery Storage Unit', category: 'Non-Profit, NGO & CleanTech', price: '$1,000+', description: 'Modular LFP battery pack providing 24h home emergency backup solar power.' }],
  },
  {
    email: 'monarch@brand.zerify.com',
    companyName: 'Monarch Timepieces',
    logoUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80',
    website: 'https://monarchwatches.ch',
    industry: 'Luxury & Designer Goods',
    location: 'Zurich, Switzerland',
    foundedYear: '2016',
    description: 'Precious metal hand-engraved dress watches crafted by master Swiss horologists.',
    socialLinks: { instagram: 'https://instagram.com/monarchwatches' },
    brandValues: ['Quality'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['35-44', '45-54', '55+'], gender: 'Male', locations: ['Switzerland', 'United States', 'United Arab Emirates'], interests: ['Luxury Goods & Designer Fashion'] },
    creatorTiers: ['Macro', 'Mega'],
    creatorLocations: ['United States', 'United Kingdom'],
    preferredCreatorGender: 'Male',
    verifiedOnly: true,
    minEngagementRate: 4.0,
    campaignBudget: '$50,000+',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'vip@monarchwatches.ch', paymentMethod: 'Swiss Bank Transfer', escrowEnabled: true },
    products: [{ name: 'Monarch Royal Gold Automatic Chronograph', category: 'Luxury Goods & Designer Fashion', price: '$1,000+', description: '18k rose gold case with hand-stitched alligator leather strap and sapphire skeleton dial.' }],
  },
  {
    email: 'veritas@brand.zerify.com',
    companyName: 'Veritas Legal AI',
    logoUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=400&q=80',
    website: 'https://veritaslegal.co.uk',
    industry: 'Consulting & Professional Services',
    location: 'London, United Kingdom',
    foundedYear: '2021',
    description: 'AI contract analysis and automated legal due-diligence software for corporate law firms.',
    socialLinks: { linkedin: 'https://linkedin.com/company/veritaslegal' },
    brandValues: ['Transparency', 'Quality'],
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['LinkedIn'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['United Kingdom', 'United States'], interests: ['Business Consulting & Corporate Services'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['United Kingdom'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$10,000 – $25,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'accounts@veritaslegal.co.uk', paymentMethod: 'Corporate Card', escrowEnabled: true },
    products: [{ name: 'Veritas Legal AI Firm License', category: 'Business Consulting & Corporate Services', price: '$799', description: 'Automated 100-page contract risk auditing in under 30 seconds with citation links.' }],
  },
  {
    email: 'pulsebeat@brand.zerify.com',
    companyName: 'PulseBeat Fitness',
    logoUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=400&q=80',
    website: 'https://pulsebeatfit.com.au',
    industry: 'Fitness & Wellness',
    location: 'Sydney, Australia',
    foundedYear: '2020',
    description: 'Heart-rate telemetry chest straps and connected group HIIT workout leaderboard displays.',
    socialLinks: { instagram: 'https://instagram.com/pulsebeatfit' },
    brandValues: ['Innovation', 'Community'],
    primaryGoals: ['Sales & Conversions', 'Brand Awareness'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['18-24', '25-34', '35-44'], gender: 'All', locations: ['Australia', 'United States'], interests: ['Fitness, Wellness & Dietary Supplements'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['Australia'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.4,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'pay@pulsebeatfit.com.au', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'PulseBeat HR Sensor Chest Strap', category: 'Fitness, Wellness & Dietary Supplements', price: '$79', description: 'ECG-accurate Bluetooth 5.0 and ANT+ dual transmission heart rate monitor.' }],
  },
  {
    email: 'omnifreight@brand.zerify.com',
    companyName: 'OmniFreight Global',
    logoUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=400&q=80',
    website: 'https://omnifreight.sg',
    industry: 'Logistics & Supply Chain',
    location: 'Singapore, Singapore',
    foundedYear: '2017',
    description: 'Real-time container tracking GPS beacons and automated customs clearance documentation.',
    socialLinks: { linkedin: 'https://linkedin.com/company/omnifreight' },
    brandValues: ['Transparency', 'Quality'],
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['LinkedIn'],
    targetAudience: { ageRanges: ['35-44', '45-54'], gender: 'All', locations: ['Singapore', 'India'], interests: ['Logistics, Freight & Supply Chain'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['Singapore'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$15,000 – $30,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'finance@omnifreight.sg', paymentMethod: 'Wire', escrowEnabled: true },
    products: [{ name: 'OmniTracker Container GPS Module', category: 'Logistics, Freight & Supply Chain', price: '$299', description: 'Solar-powered satellite GPS tracker with temperature and door-open alert sensors.' }],
  },
  {
    email: 'stellargaming@brand.zerify.com',
    companyName: 'Stellar Gaming Studio',
    logoUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
    website: 'https://stellargaming.ca',
    industry: 'Gaming & Esports Enterprises',
    location: 'Montreal, Quebec, Canada',
    foundedYear: '2021',
    description: 'Independent game development studio creating immersive sci-fi cooperative multiplayer survival titles.',
    socialLinks: { twitter: 'https://x.com/stellargames', youtube: 'https://youtube.com/@stellargaming' },
    brandValues: ['Innovation', 'Community'],
    primaryGoals: ['Product Launch', 'Community Building'],
    targetPlatforms: ['Twitch', 'YouTube', 'Twitter'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['United States', 'Canada', 'Germany'], interests: ['Esports & Gaming Organizations'] },
    creatorTiers: ['Micro', 'Mid', 'Macro'],
    creatorLocations: ['United States', 'Canada'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.8,
    campaignBudget: '$10,000 – $25,000',
    campaignFrequency: 'One-time Campaign',
    escrowSetup: { billingEmail: 'pr@stellargaming.ca', paymentMethod: 'Credit Card', escrowEnabled: true },
    products: [{ name: 'Stellar Odyssey Supporter Edition', category: 'Esports & Gaming Organizations', price: '$49', description: 'Full game Steam key + digital soundtrack + exclusive in-game space armor skin.' }],
  },
  {
    email: 'crestline@brand.zerify.com',
    companyName: 'Crestline Outdoor Gear',
    logoUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=400&q=80',
    website: 'https://crestlineoutdoor.com',
    industry: 'Sports & Outdoor Equipment',
    location: 'Vancouver, BC, Canada',
    foundedYear: '2018',
    description: 'Ultra-lightweight 4-season backpacking tents and waterproof breathable Gore-Tex alpine jackets.',
    socialLinks: { instagram: 'https://instagram.com/crestlineoutdoor' },
    brandValues: ['Quality', 'Sustainability'],
    primaryGoals: ['Brand Awareness', 'Sales & Conversions'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['Canada', 'United States'], interests: ['Outdoor, Camping & Sports Gear'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['Canada', 'United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.5,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@crestlineoutdoor.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'Crestline Alpine 2P Ultra-Light Tent', category: 'Outdoor, Camping & Sports Gear', price: '$399', description: '2.1lbs 3-season double-wall backpacking tent with DAC featherlite aluminum poles.' }],
  },
  {
    email: 'silkstone@brand.zerify.com',
    companyName: 'Silk & Stone Fashion',
    logoUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=400&q=80',
    website: 'https://silkandstone.fr',
    industry: 'Fashion & Apparel',
    location: 'Paris, France',
    foundedYear: '2019',
    description: 'Contemporary French Mulberry silk blouses, tailored trousers, and ethically sourced cashmere knits.',
    socialLinks: { instagram: 'https://instagram.com/silkandstone_paris' },
    brandValues: ['Quality', 'Inclusivity'],
    primaryGoals: ['Sales & Conversions', 'Brand Awareness'],
    targetPlatforms: ['Instagram', 'TikTok'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'Female', locations: ['France', 'United Kingdom', 'United States'], interests: ['Fashion & Apparel', 'Luxury Goods & Designer Fashion'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United Kingdom', 'France'],
    preferredCreatorGender: 'Female',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'press@silkandstone.fr', paymentMethod: 'Card', escrowEnabled: true },
    products: [{ name: 'Parisian Raw Mulberry Silk Shirt', category: 'Fashion & Apparel', price: '$210', description: '100% 22-momme pure Mulberry silk shirt with mother-of-pearl buttons.' }],
  },
  {
    email: 'hydrapure@brand.zerify.com',
    companyName: 'HydraPure Water Tech',
    logoUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=400&q=80',
    website: 'https://hydrapuretech.com',
    industry: 'Utilities & Energy',
    location: 'Tel Aviv, Israel',
    foundedYear: '2021',
    description: 'Under-sink RO water purification systems with UV sterilization and remineralization filters.',
    socialLinks: { instagram: 'https://instagram.com/hydrapuretech' },
    brandValues: ['Sustainability', 'Innovation'],
    primaryGoals: ['Lead Generation', 'Sales & Conversions'],
    targetPlatforms: ['YouTube', 'Instagram', 'Facebook'],
    targetAudience: { ageRanges: ['25-34', '35-44', '45-54'], gender: 'All', locations: ['United States', 'Israel'], interests: ['Utilities, Renewable Energy & Solar', 'Home Decor, Furniture & Interiors'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.3,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'finance@hydrapuretech.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'HydraPure 7-Stage RO System', category: 'Kitchenware & Home Appliances', price: '$499', description: 'Removes 99.99% of contaminants while adding essential calcium and magnesium minerals.' }],
  },
  {
    email: 'cognitivecloud@brand.zerify.com',
    companyName: 'Cognitive Cloud AI',
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=400&q=80',
    website: 'https://cognitivecloud.ca',
    industry: 'AI & Machine Learning',
    location: 'Toronto, Ontario, Canada',
    foundedYear: '2022',
    description: 'Enterprise generative AI copilot for customer support automation and voice AI agents.',
    socialLinks: { linkedin: 'https://linkedin.com/company/cognitivecloud', twitter: 'https://x.com/cognitive_cloud' },
    brandValues: ['Innovation', 'Quality'],
    primaryGoals: ['Lead Generation', 'User Acquisition'],
    targetPlatforms: ['LinkedIn', 'Twitter'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['Canada', 'United States'], interests: ['AI & Machine Learning', 'Software & SaaS'] },
    creatorTiers: ['Mid', 'Macro'],
    creatorLocations: ['United States', 'Canada'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.2,
    campaignBudget: '$15,000 – $30,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@cognitivecloud.ca', paymentMethod: 'Wire', escrowEnabled: true },
    products: [{ name: 'Cognitive Voice AI Agent License', category: 'AI & Machine Learning', price: '$599', description: 'Natural human voice AI agent supporting 40+ languages with zero latency response.' }],
  },

  // 21-30
  {
    email: 'urbandrive@brand.zerify.com',
    companyName: 'UrbanDrive EV',
    logoUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
    website: 'https://urbandrive.de',
    industry: 'Automotive & EV',
    location: 'Munich, Germany',
    foundedYear: '2020',
    description: 'Compact urban electric cargo bikes designed for last-mile commercial delivery fleets.',
    socialLinks: { linkedin: 'https://linkedin.com/company/urbandrive' },
    brandValues: ['Sustainability', 'Innovation'],
    primaryGoals: ['Lead Generation', 'Brand Awareness'],
    targetPlatforms: ['LinkedIn', 'YouTube'],
    targetAudience: { ageRanges: ['25-34', '35-44'], gender: 'All', locations: ['Germany', 'France'], interests: ['Automotive & EV', 'Logistics, Freight & Supply Chain'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['Germany'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 2.8,
    campaignBudget: '$10,000 – $25,000',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'fleet@urbandrive.de', paymentMethod: 'SEPA', escrowEnabled: true },
    products: [{ name: 'UrbanCargo EV Bike 300kg Payload', category: 'Automotive, Electric Vehicles & Mobility', price: '$1,000+', description: 'Heavy-duty electric cargo trike with dual removable 1.5kWh battery modules.' }],
  },
  {
    email: 'nectarteas@brand.zerify.com',
    companyName: 'Nectar Gourmet Teas',
    logoUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80',
    website: 'https://nectarteas.com',
    industry: 'Beverages & Coffee',
    location: 'Colombo, Sri Lanka',
    foundedYear: '2018',
    description: 'Single-estate Ceylon black, green, and white teas handpicked from high-altitude organic gardens.',
    socialLinks: { instagram: 'https://instagram.com/nectarteas' },
    brandValues: ['Quality', 'Sustainability'],
    primaryGoals: ['Sales & Conversions', 'Brand Awareness'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['25-34', '35-44', '45-54'], gender: 'Female', locations: ['United Kingdom', 'United States'], interests: ['Beverages, Specialty Drinks & Coffee', 'Food, Gourmet & Packaged Goods'] },
    creatorTiers: ['Nano', 'Micro'],
    creatorLocations: ['United Kingdom'],
    preferredCreatorGender: 'Female',
    verifiedOnly: false,
    minEngagementRate: 2.0,
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'export@nectarteas.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'Ceylon Imperial Silver Needle White Tea (100g)', category: 'Beverages, Specialty Drinks & Coffee', price: '$38', description: 'Rare sun-dried white tea buds with delicate floral aroma.' }],
  },
  {
    email: 'skillforge@brand.zerify.com',
    companyName: 'SkillForge EdTech',
    logoUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=400&q=80',
    website: 'https://skillforge.in',
    industry: 'EdTech & Education',
    location: 'Bengaluru, Karnataka, India',
    foundedYear: '2021',
    description: 'Cohort-based live masterclasses in Full Stack Web Development, DevOps, and Data Science.',
    socialLinks: { youtube: 'https://youtube.com/@skillforge', linkedin: 'https://linkedin.com/company/skillforge' },
    brandValues: ['Quality', 'Community'],
    primaryGoals: ['Lead Generation', 'Sales & Conversions'],
    targetPlatforms: ['YouTube', 'LinkedIn', 'Instagram'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['India'], interests: ['EdTech & Online Learning', 'Software & SaaS'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['India'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 3.0,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'finance@skillforge.in', paymentMethod: 'Razorpay', escrowEnabled: true },
    products: [{ name: 'Full Stack MERN Developer Bootcamp', category: 'EdTech & Online Learning', price: '$399', description: '6-month immersive bootcamp with guaranteed interview prep and placement assistance.' }],
  },
  {
    email: 'aerojet@brand.zerify.com',
    companyName: 'AeroJet Luxury Travel',
    logoUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=400&q=80',
    website: 'https://aerojetlux.com',
    industry: 'Travel & Lifestyle',
    location: 'Dubai, United Arab Emirates',
    foundedYear: '2019',
    description: 'On-demand private jet charter concierge and VIP luxury resort itinerary management.',
    socialLinks: { instagram: 'https://instagram.com/aerojetlux' },
    brandValues: ['Quality'],
    primaryGoals: ['Brand Awareness', 'Lead Generation'],
    targetPlatforms: ['Instagram', 'YouTube'],
    targetAudience: { ageRanges: ['35-44', '45-54', '55+'], gender: 'All', locations: ['United Arab Emirates', 'United States', 'United Kingdom'], interests: ['Travel, Tourism & Aviation', 'Luxury Goods & Designer Fashion'] },
    creatorTiers: ['Macro', 'Mega'],
    creatorLocations: ['United States', 'United Arab Emirates'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.8,
    campaignBudget: '$50,000+',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'vip@aerojetlux.com', paymentMethod: 'Wire Transfer', escrowEnabled: true },
    products: [{ name: 'Private Jet Flight Charter Hours Package', category: 'Travel, Tourism & Aviation', price: '$1,000+', description: '10-hour flight card on Gulfstream G650 private aircraft.' }],
  },
  {
    email: 'vaultdefi@brand.zerify.com',
    companyName: 'VaultDefi Protocol',
    logoUrl: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=400&q=80',
    website: 'https://vaultdefi.io',
    industry: 'Web3, Crypto & Blockchain',
    location: 'Zug, Switzerland',
    foundedYear: '2022',
    description: 'Non-custodial algorithmic yield vault protocol maximizing staking returns on Ethereum L2s.',
    socialLinks: { twitter: 'https://x.com/vaultdefi', youtube: 'https://youtube.com/@vaultdefi' },
    brandValues: ['Transparency', 'Innovation'],
    primaryGoals: ['User Acquisition', 'Community Building'],
    targetPlatforms: ['Twitter', 'YouTube', 'Telegram'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'Male', locations: ['United States', 'Switzerland', 'United Kingdom'], interests: ['Web3, Crypto & Blockchain', 'Fintech & Digital Payments'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.5,
    campaignBudget: '$15,000 – $30,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'treasury@vaultdefi.io', paymentMethod: 'USDC Escrow', escrowEnabled: true },
    products: [{ name: 'VaultDefi Staking Pass NFT', category: 'Web3, Crypto & Blockchain', price: '$350', description: 'Zero-fee auto-compounding staking vault pass with 12% APY boosts.' }],
  },
  {
    email: 'primavita@brand.zerify.com',
    companyName: 'PrimaVita Medical',
    logoUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=400&q=80',
    website: 'https://primavitamed.ch',
    industry: 'Medical Devices & Biotech',
    location: 'Basel, Switzerland',
    foundedYear: '2017',
    description: 'Non-invasive continuous glucose monitoring sensors and biometrics mobile health telemetry.',
    socialLinks: { linkedin: 'https://linkedin.com/company/primavitamed' },
    brandValues: ['Quality', 'Innovation'],
    primaryGoals: ['Lead Generation', 'Sales & Conversions'],
    targetPlatforms: ['YouTube', 'LinkedIn'],
    targetAudience: { ageRanges: ['35-44', '45-54', '55+'], gender: 'All', locations: ['Germany', 'Switzerland', 'United States'], interests: ['Medical Devices & Biotechnology', 'Healthcare & Pharmaceuticals'] },
    creatorTiers: ['Mid'],
    creatorLocations: ['United States', 'Germany'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$10,000 – $25,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'billing@primavitamed.ch', paymentMethod: 'Bank Wire', escrowEnabled: true },
    products: [{ name: 'PrimaVita CGM Sensor Starter Pack', category: 'Medical Devices & Biotechnology', price: '$199', description: 'Waterproof 14-day continuous glucose monitoring sensor with iOS/Android app integration.' }],
  },
  {
    email: 'skylinecondos@brand.zerify.com',
    companyName: 'Skyline Luxury Condos',
    logoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=400&q=80',
    website: 'https://skylinecondosmiami.com',
    industry: 'Real Estate & Property Development',
    location: 'Miami, FL, United States',
    foundedYear: '2021',
    description: 'Waterfront luxury high-rise oceanview residential condominiums with private yacht slips.',
    socialLinks: { instagram: 'https://instagram.com/skylinecondosmiami' },
    brandValues: ['Quality'],
    primaryGoals: ['Lead Generation'],
    targetPlatforms: ['Instagram', 'YouTube', 'Facebook'],
    targetAudience: { ageRanges: ['35-44', '45-54', '55+'], gender: 'All', locations: ['United States', 'Canada', 'United Kingdom'], interests: ['Real Estate & Property Development', 'Luxury Goods & Designer Fashion'] },
    creatorTiers: ['Macro', 'Mega'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.5,
    campaignBudget: '$50,000+',
    campaignFrequency: 'Quarterly Campaigns',
    escrowSetup: { billingEmail: 'sales@skylinecondosmiami.com', paymentMethod: 'Corporate Wire', escrowEnabled: true },
    products: [{ name: 'Oceanview Condo Pre-Construction Deposit', category: 'Real Estate & Property Development', price: '$1,000+', description: 'Priority selection pass for 2-bedroom oceanfront condo units in Brickell, Miami.' }],
  },
  {
    email: 'sparkpr@brand.zerify.com',
    companyName: 'SparkPR Talent Agency',
    logoUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=400&q=80',
    website: 'https://sparkpr.com',
    industry: 'Events & PR Agencies',
    location: 'New York, NY, United States',
    foundedYear: '2018',
    description: 'Full-service influencer PR seeding, red carpet event production, and brand activation management.',
    socialLinks: { instagram: 'https://instagram.com/sparkpr_ny', linkedin: 'https://linkedin.com/company/sparkpr' },
    brandValues: ['Quality', 'Innovation'],
    primaryGoals: ['Event Promotion', 'Brand Awareness'],
    targetPlatforms: ['Instagram', 'TikTok'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['United States'], interests: ['Events, PR & Talent Management', 'Fashion & Apparel'] },
    creatorTiers: ['Micro', 'Mid', 'Macro'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: true,
    minEngagementRate: 3.0,
    campaignBudget: '$20,000 – $50,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'events@sparkpr.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'NYFW Influencer Seeding Suite', category: 'Events, PR & Talent Management', price: '$999', description: 'Curated gift box distribution to top 50 fashion creators during New York Fashion Week.' }],
  },
  {
    email: 'soundwave@brand.zerify.com',
    companyName: 'SoundWave Records',
    logoUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=400&q=80',
    website: 'https://soundwaverecords.com',
    industry: 'Music & Audio Production',
    location: 'Nashville, TN, United States',
    foundedYear: '2019',
    description: 'Independent music label and Dolby Atmos spatial audio mastering studio for indie recording artists.',
    socialLinks: { instagram: 'https://instagram.com/soundwaverecords', youtube: 'https://youtube.com/@soundwaverecords' },
    brandValues: ['Innovation', 'Quality'],
    primaryGoals: ['Brand Awareness', 'Content Creation'],
    targetPlatforms: ['TikTok', 'YouTube', 'Instagram'],
    targetAudience: { ageRanges: ['18-24', '25-34'], gender: 'All', locations: ['United States', 'United Kingdom'], interests: ['Music, Audio & Podcast Production'] },
    creatorTiers: ['Micro', 'Mid'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.5,
    campaignBudget: '$5,000 – $20,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'royalties@soundwaverecords.com', paymentMethod: 'Stripe', escrowEnabled: true },
    products: [{ name: 'Dolby Atmos Spatial Audio Track Mastering', category: 'Music, Audio & Podcast Production', price: '$250', description: 'Professional 3D spatial audio mix mastering optimized for Apple Music and Tidal.' }],
  },
  {
    email: 'biobloom@brand.zerify.com',
    companyName: 'BioBloom Organics',
    logoUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=400&q=80',
    website: 'https://biobloomorganics.com',
    industry: 'Agriculture & Forestry',
    location: 'Sacramento, CA, United States',
    foundedYear: '2020',
    description: 'Organic regenerative soil amendments, bio-char microbial inoculants, and eco-farming tools.',
    socialLinks: { instagram: 'https://instagram.com/biobloomorganics' },
    brandValues: ['Sustainability', 'Quality'],
    primaryGoals: ['Sales & Conversions', 'Brand Awareness'],
    targetPlatforms: ['YouTube', 'Instagram'],
    targetAudience: { ageRanges: ['25-34', '35-44', '45-54'], gender: 'All', locations: ['United States'], interests: ['Agriculture, Forestry & AgTech', 'Outdoor, Camping & Sports Gear'] },
    creatorTiers: ['Nano', 'Micro'],
    creatorLocations: ['United States'],
    preferredCreatorGender: 'Any',
    verifiedOnly: false,
    minEngagementRate: 2.0,
    campaignBudget: '$1,000 – $5,000',
    campaignFrequency: 'Monthly Recurring',
    escrowSetup: { billingEmail: 'sales@biobloomorganics.com', paymentMethod: 'Credit Card', escrowEnabled: true },
    products: [{ name: 'BioBloom Regenerative Soil Alive Blend 50lbs', category: 'Agriculture, Forestry & AgTech', price: '$45', description: 'Enriched with mycorrhizal fungi and bio-char for maximum organic crop yield.' }],
  },
];

async function seedFakeCompanies() {
  console.log(`🚀 Seeding ${FAKE_COMPANIES.length} realistic company profiles into Neon PostgreSQL...`);

  let count = 0;
  let hundredPercentCount = 0;

  for (const company of FAKE_COMPANIES) {
    const { products, email, ...profileData } = company;
    const hasProducts = Array.isArray(products) && products.length > 0;
    const calcPercentage = calculateCompletion(profileData, hasProducts);

    if (calcPercentage === 100) hundredPercentCount++;

    // Upsert User
    const user = await prisma.user.upsert({
      where: { email },
      update: {
        name: profileData.companyName || 'Company Admin',
        role: UserRole.BRAND,
      },
      create: {
        email,
        name: profileData.companyName || 'Company Admin',
        role: UserRole.BRAND,
      },
    });

    // Upsert Brand Profile
    const profile = await prisma.brandProfile.upsert({
      where: { userId: user.id },
      update: {
        companyName: profileData.companyName || null,
        logoUrl: profileData.logoUrl || null,
        website: profileData.website || null,
        industry: profileData.industry || null,
        location: profileData.location || null,
        foundedYear: profileData.foundedYear || null,
        description: profileData.description || null,
        socialLinks: profileData.socialLinks || undefined,
        brandValues: profileData.brandValues || [],
        primaryGoals: profileData.primaryGoals || [],
        targetPlatforms: profileData.targetPlatforms || [],
        targetAudience: profileData.targetAudience || undefined,
        creatorTiers: profileData.creatorTiers || [],
        creatorLocations: profileData.creatorLocations || [],
        preferredCreatorGender: profileData.preferredCreatorGender || 'Any',
        verifiedOnly: profileData.verifiedOnly || false,
        minEngagementRate: profileData.minEngagementRate || 0.0,
        campaignBudget: profileData.campaignBudget || null,
        campaignFrequency: profileData.campaignFrequency || null,
        escrowSetup: profileData.escrowSetup || undefined,
        completionPercentage: calcPercentage,
        isOnboardingCompleted: calcPercentage >= 70,
      },
      create: {
        userId: user.id,
        companyName: profileData.companyName || null,
        logoUrl: profileData.logoUrl || null,
        website: profileData.website || null,
        industry: profileData.industry || null,
        location: profileData.location || null,
        foundedYear: profileData.foundedYear || null,
        description: profileData.description || null,
        socialLinks: profileData.socialLinks || undefined,
        brandValues: profileData.brandValues || [],
        primaryGoals: profileData.primaryGoals || [],
        targetPlatforms: profileData.targetPlatforms || [],
        targetAudience: profileData.targetAudience || undefined,
        creatorTiers: profileData.creatorTiers || [],
        creatorLocations: profileData.creatorLocations || [],
        preferredCreatorGender: profileData.preferredCreatorGender || 'Any',
        verifiedOnly: profileData.verifiedOnly || false,
        minEngagementRate: profileData.minEngagementRate || 0.0,
        campaignBudget: profileData.campaignBudget || null,
        campaignFrequency: profileData.campaignFrequency || null,
        escrowSetup: profileData.escrowSetup || undefined,
        completionPercentage: calcPercentage,
        isOnboardingCompleted: calcPercentage >= 70,
      },
    });

    // Seed Products if any
    if (products && products.length > 0) {
      await prisma.brandProduct.deleteMany({
        where: { brandProfileId: profile.id },
      });

      for (const prod of (products as any[])) {
        await prisma.brandProduct.create({
          data: {
            brandProfileId: profile.id,
            name: prod.name,
            imageUrl: prod.imageUrl || null,
            productUrl: prod.productUrl || null,
            category: prod.category || null,
            price: prod.price || null,
            description: prod.description || null,
          },
        });
      }
    }

    count++;
    console.log(`  [${count}/${FAKE_COMPANIES.length}] Seeded "${profileData.companyName}" - Completion: ${calcPercentage}% (User ID: ${user.id})`);
  }

  console.log(`\n🎉 Successfully seeded ${count} company profiles (${hundredPercentCount} at 100% completion) into the database!`);
}

seedFakeCompanies()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
