export interface IndustryCategoryGroup {
  id: string;
  category: string;
  slug: string;
  icon?: string;
  items: string[];
}

export const ALL_INDUSTRIES_GROUPED: IndustryCategoryGroup[] = [
  {
    id: 'tech-ai',
    category: 'Technology & AI',
    slug: 'technology-ai',
    icon: 'Cpu',
    items: [
      'Tech & SaaS',
      'Artificial Intelligence & ML',
      'Consumer Electronics & Gadgets',
      'Developer Tools & APIs',
      'Cybersecurity & Privacy',
      'Web3, Blockchain & Crypto',
      'Cloud Computing & DevOps',
      'Robotics & Hardware',
    ],
  },
  {
    id: 'fashion-apparel',
    category: 'Fashion & Apparel',
    slug: 'fashion-apparel',
    icon: 'Shirt',
    items: [
      'Luxury & High Fashion',
      'Streetwear & Urban',
      'Sustainable & Ethical Fashion',
      'Footwear & Sneakers',
      'Jewelry, Watches & Accessories',
      'Swimwear & Activewear',
      'Vintage & Thrift',
      'Plus Size & Inclusive Fashion',
    ],
  },
  {
    id: 'beauty-grooming',
    category: 'Beauty, Skincare & Grooming',
    slug: 'beauty-grooming',
    icon: 'Sparkles',
    items: [
      'Skincare & Dermatological',
      'Makeup & Color Cosmetics',
      'Haircare & Styling',
      'Fragrance & Perfumery',
      'Men’s Grooming & Shaving',
      'Clean Beauty & Organic',
      'Nail Art & Care',
      'Body Care & Spa',
    ],
  },
  {
    id: 'health-fitness',
    category: 'Health, Wellness & Fitness',
    slug: 'health-fitness',
    icon: 'Activity',
    items: [
      'Gym, Bodybuilding & Strength',
      'Supplements & Sports Nutrition',
      'Yoga, Pilates & Mindfulness',
      'Athletics, Running & Cycling',
      'Mental Health & Sleep Tech',
      'Outdoor Adventure & Camping',
      'Biohacking & Longevity',
      'Physiotherapy & Recovery',
    ],
  },
  {
    id: 'food-beverage',
    category: 'Food, Beverage & Culinary',
    slug: 'food-beverage',
    icon: 'Utensils',
    items: [
      'Specialty Coffee & Artisan Tea',
      'Gourmet Dining & Restaurants',
      'Healthy Snacks & Functional Drinks',
      'Vegan & Plant-Based Food',
      'Wine, Spirits & Craft Beer',
      'Cooking, Baking & Recipes',
      'Meal Kits & Food Delivery',
      'Barbecue & Grilling',
    ],
  },
  {
    id: 'gaming-esports',
    category: 'Gaming, Esports & Entertainment',
    slug: 'gaming-esports',
    icon: 'Gamepad2',
    items: [
      'PC & Console Gaming',
      'Mobile Gaming & Apps',
      'Esports & Competitive Gaming',
      'Live Streaming & Content Creation',
      'Anime, Comics & Pop Culture',
      'Film, TV & Cinema',
      'Podcasts & Audiobooks',
      'Board Games & Tabletop',
    ],
  },
  {
    id: 'travel-hospitality',
    category: 'Travel, Tourism & Hospitality',
    slug: 'travel-hospitality',
    icon: 'Plane',
    items: [
      'Luxury Resorts & Hotels',
      'Budget, Backpacking & Solo Travel',
      'Airlines & Cruise Lines',
      'Digital Nomad & Van Life',
      'City Guides & Urban Exploration',
      'Eco-Tourism & Nature Expeditions',
      'Road Trips & Glamping',
    ],
  },
  {
    id: 'finance-crypto',
    category: 'Finance, Crypto & Real Estate',
    slug: 'finance-crypto',
    icon: 'BadgeDollarSign',
    items: [
      'Personal Finance & Budgeting',
      'Fintech & Digital Banking',
      'Stock Trading & Investments',
      'Crypto & DeFi',
      'Real Estate, Property & PropTech',
      'Startups, VC & Entrepreneurship',
      'Accounting & Tax Planning',
    ],
  },
  {
    id: 'education-career',
    category: 'Education, Career & Productivity',
    slug: 'education-career',
    icon: 'GraduationCap',
    items: [
      'EdTech & Online Courses',
      'Productivity Tools & Systems',
      'Career Coaching & Resume Building',
      'Language Learning',
      'STEM, Coding & Science',
      'Books & Personal Development',
      'Business & Leadership',
    ],
  },
  {
    id: 'home-living',
    category: 'Home, Living & Interior Design',
    slug: 'home-living',
    icon: 'Home',
    items: [
      'Interior Design & Architecture',
      'Smart Home & IoT Devices',
      'Furniture & Home Decor',
      'Gardening & Plant Care',
      'Kitchenware & Appliances',
      'DIY & Home Improvement',
      'Organization & Decluttering',
    ],
  },
  {
    id: 'automotive-mobility',
    category: 'Automotive & Mobility',
    slug: 'automotive-mobility',
    icon: 'Car',
    items: [
      'Electric Vehicles (EV) & Clean Tech',
      'Supercars & High Performance',
      'Car Reviews & Detailing',
      'Motorcycles & Powersports',
      'Bicycles & Micro-Mobility',
      'Automotive DIY & Tuning',
    ],
  },
  {
    id: 'family-parenting',
    category: 'Family, Parenting & Kids',
    slug: 'family-parenting',
    icon: 'Baby',
    items: [
      'Baby & Toddler Essentials',
      'Parenting Advice & Family Life',
      'Kids Toys, Games & Books',
      'Maternity & Postpartum Care',
      'Family Travel & Activities',
    ],
  },
  {
    id: 'pets-animals',
    category: 'Pets & Animals',
    slug: 'pets-animals',
    icon: 'PawPrint',
    items: [
      'Dog Care, Nutrition & Training',
      'Cat Products & Toys',
      'Pet Health, Veterinary & Supplements',
      'Aquariums & Exotic Pets',
      'Equine & Horse Riding',
    ],
  },
  {
    id: 'art-music',
    category: 'Art, Design & Music',
    slug: 'art-music',
    icon: 'Palette',
    items: [
      'Digital Art, 3D & VFX',
      'Photography & Filmmaking Gear',
      'Music Production, DJing & Audio',
      'Graphic Design, Fonts & UI/UX',
      'Painting, Illustration & Crafts',
    ],
  },
  {
    id: 'social-impact',
    category: 'Social Impact & Non-Profit',
    slug: 'social-impact',
    icon: 'HeartHandshake',
    items: [
      'Sustainability & Climate Action',
      'Charities & Social Causes',
      'Community Organizing & Activism',
      'Mental Health Advocacy',
    ],
  },
  {
    id: 'ecommerce-retail',
    category: 'E-Commerce & Retail',
    slug: 'ecommerce-retail',
    icon: 'ShoppingBag',
    items: [
      'Direct to Consumer (DTC) Brands',
      'Boutique Marketplace & Crafts',
      'Subscription Boxes',
      'Consumer Goods (FMCG)',
    ],
  },
];

export const ALL_INDUSTRIES_FLAT: string[] = ALL_INDUSTRIES_GROUPED.flatMap(
  (group) => group.items,
);

export const PRIMARY_CATEGORY_NAMES: string[] = ALL_INDUSTRIES_GROUPED.map(
  (group) => group.category,
);

export const SUGGESTED_OBJECTIVE_TAGS: string[] = [
  'Brand Awareness',
  'Product Launch',
  'Website Traffic',
  'App Installs',
  'Lead Generation',
  'Sales & Conversions',
  'UGC Creation',
  'Social Growth',
  'Community Building',
  'Influencer Gifting',
  'Event Promotion',
  'Brand Recall',
  'Customer Testimonials',
  'Affiliate Expansion',
];
