import { CreatorItem } from './CreatorCard';

export const MOCK_CREATORS: CreatorItem[] = [
  {
    id: 'c1',
    name: 'Leo Dupont',
    handle: '@leodupont_audio',
    role: 'Music Producer & Audio Gear Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    category: 'Music Production',
    categories: ['Music Production', 'Audio Equipment', 'Sound Design', 'Studio Tech'],
    bio: 'Music Producer & Audio Gear Engineer in Paris 🎧 Testing studio planar headphones, analog synths & DAW plugins.',
    reach: '92K',
    reachNumber: 92000,
    engRate: '4.9%',
    engRateNumber: 4.9,
    rating: 4.8,
    startingRate: '$500',
    rateNumber: 500,
    platforms: ['YouTube'],
    primaryPlatform: 'YouTube',
    location: 'Paris, France',
    statusText: 'Available for Collabs',
    matchScore: 97,
    matchReasons: [
      'Top tier acoustic audience engagement in audio gear reviews',
      'High conversion on pro audio monitors and studio plugins',
      'Consistent 4.9% engagement rate on YouTube teardowns',
    ],
    isVerified: true,
    skills: ['Audio Gear Reviews', 'DAW Walkthroughs', 'Hardware Demos', 'Studio Teardowns'],
    topAudienceAge: '25-34 (54%)',
    topAudienceGender: '72% Male / 28% Female',
    creatorTier: 'Micro (10K - 100K)',
  },
  {
    id: 'c2',
    name: 'Sarah Jenkins',
    handle: '@sarah_creativ',
    role: 'AI Workflow & Tech Systems Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    category: 'Technology & AI',
    categories: ['Technology & AI', 'Productivity Tools', 'SaaS Tutorials', 'Dev Systems'],
    bio: 'AI workflows, productivity tools, and modern software engineering tutorials with deep-dive teardowns.',
    reach: '485K',
    reachNumber: 485000,
    engRate: '6.8%',
    engRateNumber: 6.8,
    rating: 4.9,
    startingRate: '$850',
    rateNumber: 850,
    platforms: ['YouTube', 'Twitter', 'LinkedIn'],
    primaryPlatform: 'YouTube',
    location: 'San Francisco, CA, United States',
    statusText: 'Available for Collabs',
    matchScore: 96,
    matchReasons: [
      'Tech audience aligns 96% with AI SaaS products',
      'High conversion on developer tools tutorials',
      'Consistent 6.8% engagement rate on YouTube shorts',
    ],
    isVerified: true,
    skills: ['Video Tutorials', 'YouTube Shorts', 'Product Walkthrough', 'Twitter Thread'],
    topAudienceAge: '25-34 (64%)',
    topAudienceGender: '62% Male / 38% Female',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c3',
    name: 'Marcus Vance',
    handle: '@marcus_vfit',
    role: 'Performance Athletics & Functional Trainer',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
    category: 'Fitness & Wellness',
    categories: ['Fitness & Wellness', 'Performance Gear', 'Athletic Nutrition', 'Strength'],
    bio: 'High-intensity athletic training, functional nutrition, and performance wearable gear reviews.',
    reach: '620K',
    reachNumber: 620000,
    engRate: '8.1%',
    engRateNumber: 8.1,
    rating: 5.0,
    startingRate: '$1,200',
    rateNumber: 1200,
    platforms: ['Instagram', 'YouTube', 'TikTok'],
    primaryPlatform: 'Instagram',
    location: 'Austin, TX, United States',
    statusText: 'Accepting Q3 Deals',
    matchScore: 94,
    matchReasons: [
      'Top-tier engagement in activewear & athletic supplements',
      '5.0-star rating across 24 verified brand deals',
      'High save rate on workout routines',
    ],
    isVerified: true,
    skills: ['Reels / Shorts', 'Story Sequences', 'Supplement Reviews', 'Brand Ambassador'],
    topAudienceAge: '18-24 (45%), 25-34 (40%)',
    topAudienceGender: '55% Male / 45% Female',
    creatorTier: 'Macro (500K - 1M)',
  },
  {
    id: 'c4',
    name: 'Elena Rostova',
    handle: '@elena_glow',
    role: 'Clean Botanical Skincare Formulator',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
    category: 'Beauty, Skincare & Grooming',
    categories: ['Beauty, Skincare & Grooming', 'Clean Cosmetics', 'Derm Routines'],
    bio: 'Dermatologist-approved clean skincare routines, botanical ingredient breakdowns, and glowing glam looks.',
    reach: '290K',
    reachNumber: 290000,
    engRate: '7.4%',
    engRateNumber: 7.4,
    rating: 4.8,
    startingRate: '$650',
    rateNumber: 650,
    platforms: ['TikTok', 'Instagram'],
    primaryPlatform: 'TikTok',
    location: 'Los Angeles, CA, United States',
    statusText: 'Available for Collabs',
    matchScore: 92,
    matchReasons: [
      '82% female demographic matching beauty skincare launches',
      'Viral TikTok reach with clean skincare formulas',
    ],
    isVerified: true,
    skills: ['TikTok Videos', 'GRWM Reels', 'Ingredient Breakdown', 'Product Hauls'],
    topAudienceAge: '18-24 (58%), 25-34 (32%)',
    topAudienceGender: '84% Female / 16% Male',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c5',
    name: 'Chloe Monet',
    handle: '@chloe_couture',
    role: 'Sustainable Parisian Fashion Stylist',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
    category: 'Fashion & Apparel',
    categories: ['Fashion & Apparel', 'Capsule Wardrobes', 'Luxury Accessories'],
    bio: 'Sustainable capsule wardrobes, Parisian chic fashion styling, and luxury accessory showcases.',
    reach: '350K',
    reachNumber: 350000,
    engRate: '8.7%',
    engRateNumber: 8.7,
    rating: 4.9,
    startingRate: '$900',
    rateNumber: 900,
    platforms: ['Instagram', 'TikTok', 'YouTube'],
    primaryPlatform: 'Instagram',
    location: 'Paris, France',
    statusText: 'Available for Collabs',
    matchScore: 91,
    matchReasons: [
      'High European & US luxury audience affinity',
      '8.7% ER with exceptional photo aesthetics',
    ],
    isVerified: true,
    skills: ['Editorial Lookbooks', 'OOTD Reels', 'Capsule Wardrobes', 'Story Series'],
    topAudienceAge: '25-34 (55%)',
    topAudienceGender: '76% Female / 24% Male',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c6',
    name: 'David Zhao',
    handle: '@davidzhao_cooks',
    role: 'Artisan Culinary Chef & Food Creator',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
    category: 'Food, Beverage & Culinary',
    categories: ['Food, Beverage & Culinary', 'Artisan Coffee', 'Gourmet Recipes'],
    bio: '15-minute gourmet meals, artisan coffee brews, and restaurant kitchen secret recipes.',
    reach: '540K',
    reachNumber: 540000,
    engRate: '9.2%',
    engRateNumber: 9.2,
    rating: 5.0,
    startingRate: '$1,100',
    rateNumber: 1100,
    platforms: ['TikTok', 'Instagram', 'YouTube'],
    primaryPlatform: 'TikTok',
    location: 'Vancouver, Canada',
    statusText: 'Available for Collabs',
    matchScore: 95,
    matchReasons: [
      'Exceptional 9.2% engagement rate across food recipes',
      'High bookmark & recipe reproduction rate',
    ],
    isVerified: true,
    skills: ['Recipe Reels', 'Kitchen Gadget Reviews', 'Food Tasting', 'Brand Ambassador'],
    topAudienceAge: '25-34 (48%), 35-44 (28%)',
    topAudienceGender: '52% Female / 48% Male',
    creatorTier: 'Macro (500K - 1M)',
  },
  {
    id: 'c7',
    name: 'Maya Lin',
    handle: '@mayavoyage',
    role: 'Cinematic Travel Documentarian',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
    category: 'Travel, Hospitality & Tourism',
    categories: ['Travel, Hospitality & Tourism', 'Eco-Resorts', 'Drone Video'],
    bio: 'Solo adventure travel, boutique eco-resorts, and cinematic drone storytelling across 45 countries.',
    reach: '195K',
    reachNumber: 195000,
    engRate: '7.9%',
    engRateNumber: 7.9,
    rating: 4.8,
    startingRate: '$500',
    rateNumber: 500,
    platforms: ['Instagram', 'YouTube'],
    primaryPlatform: 'Instagram',
    location: 'London, United Kingdom',
    statusText: 'Available for Collabs',
    matchScore: 88,
    matchReasons: [
      'High engagement travel enthusiast demographic',
      'Cinematic 4K drone reels & hotel photography',
    ],
    isVerified: false,
    skills: ['Cinematic Drone Video', 'Hotel Reviews', 'Travel Guides', 'Photography'],
    topAudienceAge: '25-34 (58%)',
    topAudienceGender: '60% Female / 40% Male',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c8',
    name: 'Julian Sterling',
    handle: '@julianfin',
    role: 'Quantitative Finance & Wealth Strategist',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    category: 'Finance, Crypto & Investing',
    categories: ['Finance, Crypto & Investing', 'Fintech Tools', 'Wealth Building'],
    bio: 'Smart personal finance, passive income building, stock market breakdowns, and financial freedom.',
    reach: '720K',
    reachNumber: 720000,
    engRate: '6.4%',
    engRateNumber: 6.4,
    rating: 4.9,
    startingRate: '$1,500',
    rateNumber: 1500,
    platforms: ['YouTube', 'Twitter', 'LinkedIn'],
    primaryPlatform: 'YouTube',
    location: 'New York, NY, United States',
    statusText: 'Available for Collabs',
    matchScore: 90,
    matchReasons: [
      'High conversion for fintech apps & investment tools',
      'Affluent high-earning viewer demographic',
    ],
    isVerified: true,
    skills: ['Deep-Dive Videos', 'Fintech Sponsorships', 'Twitter Spaces', 'Case Studies'],
    topAudienceAge: '25-34 (52%), 35-44 (30%)',
    topAudienceGender: '72% Male / 28% Female',
    creatorTier: 'Macro (500K - 1M)',
  },
];
