import { CreatorItem } from './CreatorCard';

export const MOCK_CREATORS: CreatorItem[] = [
  {
    id: 'c1',
    name: 'Sarah Jenkins',
    handle: '@sarah_creativ',
    category: 'Technology & AI',
    bio: 'AI workflows, productivity tools, and modern software engineering tutorials with deep-dive teardowns.',
    reach: '485K',
    reachNumber: 485000,
    engRate: '6.8%',
    engRateNumber: 6.8,
    rating: 4.9,
    startingRate: '$850',
    rateNumber: 850,
    platforms: ['YouTube', 'Twitter', 'LinkedIn'],
    primaryPlatform: 'YouTube',
    location: 'San Francisco, CA, United States',
    matchScore: 96,
    matchReasons: [
      'Tech audience aligns 96% with AI SaaS products',
      'High conversion on developer tools tutorials',
      'Consistent 6.8% engagement rate on YouTube shorts',
    ],
    isVerified: true,
    skills: ['Video Tutorials', 'YouTube Shorts', 'Product Walkthrough', 'Twitter Thread'],
    topAudienceAge: '25-34 (64%)',
    topAudienceGender: '62% Male / 38% Female',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c2',
    name: 'Marcus Vance',
    handle: '@marcus_vfit',
    category: 'Fitness & Wellness',
    bio: 'High-intensity athletic training, functional nutrition, and performance wearable gear reviews.',
    reach: '620K',
    reachNumber: 620000,
    engRate: '8.1%',
    engRateNumber: 8.1,
    rating: 5.0,
    startingRate: '$1,200',
    rateNumber: 1200,
    platforms: ['Instagram', 'YouTube', 'TikTok'],
    primaryPlatform: 'Instagram',
    location: 'Austin, TX, United States',
    matchScore: 94,
    matchReasons: [
      'Top-tier engagement in activewear & athletic supplements',
      '5.0-star rating across 24 verified brand deals',
      'High save rate on workout routines',
    ],
    isVerified: true,
    skills: ['Reels / Shorts', 'Story Sequences', 'Supplement Reviews', 'Brand Ambassador'],
    topAudienceAge: '18-24 (45%), 25-34 (40%)',
    topAudienceGender: '55% Male / 45% Female',
    creatorTier: 'Macro (500K - 1M)',
  },
  {
    id: 'c3',
    name: 'Elena Rostova',
    handle: '@elena_glow',
    category: 'Beauty, Skincare & Grooming',
    bio: 'Dermatologist-approved clean skincare routines, botanical ingredient breakdowns, and glowing glam looks.',
    reach: '290K',
    reachNumber: 290000,
    engRate: '7.4%',
    engRateNumber: 7.4,
    rating: 4.8,
    startingRate: '$650',
    rateNumber: 650,
    platforms: ['TikTok', 'Instagram'],
    primaryPlatform: 'TikTok',
    location: 'Los Angeles, CA, United States',
    matchScore: 92,
    matchReasons: [
      '82% female demographic matching beauty skincare launches',
      'Viral TikTok reach with clean skincare formulas',
    ],
    isVerified: true,
    skills: ['TikTok Videos', 'GRWM Reels', 'Ingredient Breakdown', 'Product Hauls'],
    topAudienceAge: '18-24 (58%), 25-34 (32%)',
    topAudienceGender: '84% Female / 16% Male',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c4',
    name: 'Alex Rivera',
    handle: '@alex_tech',
    category: 'Technology & AI',
    bio: 'Unboxing the coolest consumer tech, custom PC setups, and next-gen gaming hardware.',
    reach: '810K',
    reachNumber: 810000,
    engRate: '5.9%',
    engRateNumber: 5.9,
    rating: 4.9,
    startingRate: '$1,800',
    rateNumber: 1800,
    platforms: ['YouTube', 'Twitch', 'Twitter'],
    primaryPlatform: 'YouTube',
    location: 'Seattle, WA, United States',
    matchScore: 89,
    matchReasons: [
      'High-intent tech buyers and gamers',
      'High production value in 4K studio setup',
    ],
    isVerified: true,
    skills: ['Dedicated Videos', 'Live Stream Integrations', 'Unboxings', 'Comparison Reviews'],
    topAudienceAge: '18-24 (48%), 25-34 (42%)',
    topAudienceGender: '78% Male / 22% Female',
    creatorTier: 'Macro (500K - 1M)',
  },
  {
    id: 'c5',
    name: 'Chloe Monet',
    handle: '@chloe_couture',
    category: 'Fashion & Apparel',
    bio: 'Sustainable capsule wardrobes, Parisian chic fashion styling, and luxury accessory showcases.',
    reach: '350K',
    reachNumber: 350000,
    engRate: '8.7%',
    engRateNumber: 8.7,
    rating: 4.9,
    startingRate: '$900',
    rateNumber: 900,
    platforms: ['Instagram', 'TikTok', 'YouTube'],
    primaryPlatform: 'Instagram',
    location: 'Paris, France',
    matchScore: 91,
    matchReasons: [
      'High European & US luxury audience affinity',
      '8.7% ER with exceptional photo aesthetics',
    ],
    isVerified: true,
    skills: ['Editorial Lookbooks', 'OOTD Reels', 'Capsule Wardrobes', 'Story Series'],
    topAudienceAge: '25-34 (55%)',
    topAudienceGender: '76% Female / 24% Male',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c6',
    name: 'David Zhao',
    handle: '@davidzhao_cooks',
    category: 'Food, Beverage & Culinary',
    bio: '15-minute gourmet meals, artisan coffee brews, and restaurant kitchen secret recipes.',
    reach: '540K',
    reachNumber: 540000,
    engRate: '9.2%',
    engRateNumber: 9.2,
    rating: 5.0,
    startingRate: '$1,100',
    rateNumber: 1100,
    platforms: ['TikTok', 'Instagram', 'YouTube'],
    primaryPlatform: 'TikTok',
    location: 'Vancouver, Canada',
    matchScore: 95,
    matchReasons: [
      'Exceptional 9.2% engagement rate across food recipes',
      'High bookmark & recipe reproduction rate',
    ],
    isVerified: true,
    skills: ['Recipe Reels', 'Kitchen Gadget Reviews', 'Food Tasting', 'Brand Ambassador'],
    topAudienceAge: '25-34 (48%), 35-44 (28%)',
    topAudienceGender: '52% Female / 48% Male',
    creatorTier: 'Macro (500K - 1M)',
  },
  {
    id: 'c7',
    name: 'Maya Lin',
    handle: '@mayavoyage',
    category: 'Travel, Hospitality & Tourism',
    bio: 'Solo adventure travel, boutique eco-resorts, and cinematic drone storytelling across 45 countries.',
    reach: '195K',
    reachNumber: 195000,
    engRate: '7.9%',
    engRateNumber: 7.9,
    rating: 4.8,
    startingRate: '$500',
    rateNumber: 500,
    platforms: ['Instagram', 'YouTube'],
    primaryPlatform: 'Instagram',
    location: 'London, United Kingdom',
    matchScore: 88,
    matchReasons: [
      'High engagement travel enthusiast demographic',
      'Cinematic 4K drone reels & hotel photography',
    ],
    isVerified: false,
    skills: ['Cinematic Drone Video', 'Hotel Reviews', 'Travel Guides', 'Photography'],
    topAudienceAge: '25-34 (58%)',
    topAudienceGender: '60% Female / 40% Male',
    creatorTier: 'Mid-Tier (100K - 500K)',
  },
  {
    id: 'c8',
    name: 'Julian Sterling',
    handle: '@julianfin',
    category: 'Finance, Crypto & Investing',
    bio: 'Smart personal finance, passive income building, stock market breakdowns, and financial freedom.',
    reach: '720K',
    reachNumber: 720000,
    engRate: '6.4%',
    engRateNumber: 6.4,
    rating: 4.9,
    startingRate: '$1,500',
    rateNumber: 1500,
    platforms: ['YouTube', 'Twitter', 'LinkedIn'],
    primaryPlatform: 'YouTube',
    location: 'New York, NY, United States',
    matchScore: 90,
    matchReasons: [
      'High conversion for fintech apps & investment tools',
      'Affluent high-earning viewer demographic',
    ],
    isVerified: true,
    skills: ['Deep-Dive Videos', 'Fintech Sponsorships', 'Twitter Spaces', 'Case Studies'],
    topAudienceAge: '25-34 (52%), 35-44 (30%)',
    topAudienceGender: '72% Male / 28% Female',
    creatorTier: 'Macro (500K - 1M)',
  },
];
